### ISSUE TITLE
执行米游币任务的可选频道里空了

### ISSUE THREAD

**Issue by laurelcafe** [Ljzd-PRO/nonebot-plugin-mystool#107]
执行米游币任务的可选频道里空了，然后每天自动执行的时候就报错停止了，重新装了一边也没有，也不知道什么原因导致的。
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/43950231/abe24ecd-69c2-4a18-8db3-58abdbefc44e)

**Comment by laurelcafe** [comment]
但跑了一下，米游币任务能跑，签到反而跑不了

Running Matcher(type='message', module=nonebot_plugin_mystool.plan) failed.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/usr/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/message.py", line 141, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/usr/local/lib/python3.10/dist-packages/nonebot/message.py", line 187, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/internal/matcher/matcher.py", line 753, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/internal/matcher/matcher.py", line 728, in simple_run
    await handler(
  File "/usr/local/lib/python3.10/dist-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/usr/local/lib/python3.10/dist-packages/nonebot_plugin_mystool/plan.py", line 35, in _
    await perform_game_sign(bot=bot, qq=event.user_id, is_auto=False, group_event=event)
  File "/usr/local/lib/python3.10/dist-packages/nonebot_plugin_mystool/plan.py", line 121, in perform_game_sign
    if GameInfo.ABBR_TO_ID[record.game_id][0] not in GameSign.SUPPORTED_GAMES:
KeyError: 2

**Comment by Ljzd-PRO** [comment]
这个账号有注册了哪些米哈游游戏呢

**Comment by laurelcafe** [comment]
两个号。一个号是原神，一个号是原神、崩坏3、星穹铁道、崩坏2、未定。

**Comment by laurelcafe** [comment]
我把环境重新配置一遍就好了，问题我关了
