### ISSUE TITLE
更新到0.2.9后生成商品图片报错

### ISSUE THREAD

**Issue by Sakamakiiizayoi** [Ljzd-PRO/nonebot-plugin-mystool#108]
更新到版本0.2.9之后 只要执行/商品 xx 后台立刻报错而且插件就此暴毙 没有反应了 必须重开机器人 报错信息如下
```python
Process SpawnPoolWorker-4:
Process SpawnPoolWorker-3:
Process SpawnPoolWorker-2:
Process SpawnPoolWorker-5:
Process SpawnPoolWorker-6:
Process SpawnPoolWorker-7:
Traceback (most recent call last):
Traceback (most recent call last):
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
Traceback (most recent call last):
Traceback (most recent call last):
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 114, in worker
    task = get()
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\multiprocessing\queues.py", line 367, in get
    return _ForkingPickler.loads(res)
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 114, in worker
    task = get()
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 114, in worker
    task = get()
  File "C:\Users\xxxx\Desktop\mysbot\.venv\lib\site-packages\nonebot_plugin_mystool\__init__.py", line 40, in <module>
    from .data import create_files
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\multiprocessing\queues.py", line 367, in get
    return _ForkingPickler.loads(res)
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 114, in worker
    task = get()
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\multiprocessing\queues.py", line 367, in get
    return _ForkingPickler.loads(res)
  File "C:\Users\xxxx\Desktop\mysbot\.venv\lib\site-packages\nonebot_plugin_mystool\data.py", line 9, in <module>
    from .config import PATH
  File "C:\Users\xxxx\Desktop\mysbot\.venv\lib\site-packages\nonebot_plugin_mystool\__init__.py", line 40, in <module>
    from .data import create_files
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 114, in worker
    task = get()
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\multiprocessing\queues.py", line 367, in get
    return _ForkingPickler.loads(res)
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\multiprocessing\queues.py", line 367, in get
    return _ForkingPickler.loads(res)
  File "C:\Users\xxxx\Desktop\mysbot\.venv\lib\site-packages\nonebot_plugin_mystool\__init__.py", line 40, in <module>
    from .data import create_files
  File "C:\Users\xxxx\Desktop\mysbot\.venv\lib\site-packages\nonebot_plugin_mystool\config.py", line 24, in <module>
    driver = get_driver()
  File "C:\Users\xxxx\Desktop\mysbot\.venv\lib\site-packages\nonebot_plugin_mystool\data.py", line 9, in <module>
    from .config import PATH
  File "C:\Users\xxxx\Desktop\mysbot\.venv\lib\site-packages\nonebot_plugin_mystool\config.py", line 24, in <module>
    driver = get_driver()
  File "C:\Users\xxxx\Desktop\mysbot\.venv\lib\site-packages\nonebot_plugin_mystool\__init__.py", line 40, in <module>
    from .data import create_files
  File "C:\Users\xxxx\Desktop\mysbot\.venv\lib\site-packages\nonebot_plugin_mystool\__init__.py", line 40, in <module>
    from .data import create_files
  File "C:\Users\xxxx\Desktop\mysbot\.venv\lib\site-packages\nonebot_plugin_mystool\data.py", line 9, in <module>
    from .config import PATH
  File "C:\Users\xxxx\Desktop\mysbot\.venv\lib\site-packages\nonebot\__init__.py", line 79, in get_driver
    raise ValueError("NoneBot has not been initialized.")
ValueError: NoneBot has not been initialized.
  File "C:\Users\xxxx\Desktop\mysbot\.venv\lib\site-packages\nonebot\__init__.py", line 79, in get_driver
    raise ValueError("NoneBot has not been initialized.")
  File "C:\Users\xxxx\Desktop\mysbot\.venv\lib\site-packages\nonebot_plugin_mystool\data.py", line 9, in <module>
    from .config import PATH
  File "C:\Users\xxxx\Desktop\mysbot\.venv\lib\site-packages\nonebot_plugin_mystool\data.py", line 9, in <module>
    from .config import PATH
  File "C:\Users\xxxx\Desktop\mysbot\.venv\lib\site-packages\nonebot_plugin_mystool\config.py", line 24, in <module>
    driver = get_driver()
Traceback (most recent call last):
ValueError: NoneBot has not been initialized.
  File "C:\Users\xxxx\Desktop\mysbot\.venv\lib\site-packages\nonebot_plugin_mystool\config.py", line 24, in <module>
    driver = get_driver()
  File "C:\Users\xxxx\Desktop\mysbot\.venv\lib\site-packages\nonebot_plugin_mystool\config.py", line 24, in <module>
    driver = get_driver()
  File "C:\Users\xxxx\Desktop\mysbot\.venv\lib\site-packages\nonebot\__init__.py", line 79, in get_driver
    raise ValueError("NoneBot has not been initialized.")
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\xxxx\Desktop\mysbot\.venv\lib\site-packages\nonebot\__init__.py", line 79, in get_driver
    raise ValueError("NoneBot has not been initialized.")
  File "C:\Users\xxxx\Desktop\mysbot\.venv\lib\site-packages\nonebot\__init__.py", line 79, in get_driver
    raise ValueError("NoneBot has not been initialized.")
ValueError: NoneBot has not been initialized.
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
ValueError: NoneBot has not been initialized.
ValueError: NoneBot has not been initialized.
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 114, in worker
    task = get()
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python310\lib\multiprocessing\queues.py", line 367, in get
    return _ForkingPickler.loads(res)
  File "C:\Users\xxxx\Desktop\mysbot\.venv\lib\site-packages\nonebot_plugin_mystool\__init__.py", line 40, in <module>
    from .data import create_files
  File "C:\Users\xxxx\Desktop\mysbot\.venv\lib\site-packages\nonebot_plugin_mystool\data.py", line 9, in <module>
    from .config import PATH
  File "C:\Users\xxxx\Desktop\mysbot\.venv\lib\site-packages\nonebot_plugin_mystool\config.py", line 24, in <module>
    driver = get_driver()
  File "C:\Users\xxxx\Desktop\mysbot\.venv\lib\site-packages\nonebot\__init__.py", line 79, in get_driver
    raise ValueError("NoneBot has not been initialized.")
ValueError: NoneBot has not been initialized.
```

**Comment by Sakamakiiizayoi** [comment]
安装回0.2.8生成data\nonebot-plugin-mystool下商品图片 再安装回0.2.9就没问题 好像是生成图片有点问题

**Comment by Ljzd-PRO** [comment]
确实是和商品图片生成有关，但我这里Linux下是可以正常运行和生成图片的。
看上去是创建多进程的时候没有把nonebot实例复制过去导致的，不过我这里没有这个问题，应该也是好解决，避开调用nonebot应该就可以。

**Comment by fanlu** [comment]
我也遇到这个问题了，0.2.9版本 macos下面

**Comment by Ljzd-PRO** [comment]
> 我也遇到这个问题了，0.2.9版本 macos下面

macOS和Windows平台的Python `multiprocessing` 多进程只支持`spawn`模式启动，导致重复导入各个代码文件，其中有些会执行`nonebot.get_bot`函数，由于新进程并没有启动新的nonebot实例，导致出错。
https://docs.python.org/zh-cn/3/library/multiprocessing.html#contexts-and-start-methods

目前还在找解决方法，可以先使用 v0.2.8

**Comment by fanlu** [comment]
> > 我也遇到这个问题了，0.2.9版本 macos下面
> 
> macOS和Windows平台的Python `multiprocessing` 多进程只支持`spawn`模式启动，导致重复导入各个代码文件，其中有些会执行`nonebot.get_bot`函数，由于新进程并没有启动新的nonebot实例，导致出错。 https://docs.python.org/zh-cn/3/library/multiprocessing.html#contexts-and-start-methods
> 
> 目前还在找解决方法，可以先使用 v0.2.8

刚才降级到0.2.8，重启后发现之前QQ注册的号码需要重新“登录”，发送“登录”命令后，后台进程疯狂的发信息，导致QQ被封禁一天
<img width="447" alt="image" src="https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/1620875/4f955882-0e86-42eb-84fb-b98a31ae0aec">

**Comment by Ljzd-PRO** [comment]
> > > 我也遇到这个问题了，0.2.9版本 macos下面
> > 
> > 
> > macOS和Windows平台的Python `multiprocessing` 多进程只支持`spawn`模式启动，导致重复导入各个代码文件，其中有些会执行`nonebot.get_bot`函数，由于新进程并没有启动新的nonebot实例，导致出错。 https://docs.python.org/zh-cn/3/library/multiprocessing.html#contexts-and-start-methods
> > 目前还在找解决方法，可以先使用 v0.2.8
> 
> 刚才降级到0.2.8，重启后发现之前QQ注册的号码需要重新“登录”，发送“登录”命令后，后台进程疯狂的发信息，导致QQ被封禁一天 <img alt="image" width="447" src="https://user-images.githubusercontent.com/1620875/245655914-4f955882-0e86-42eb-84fb-b98a31ae0aec.png">

是不断在QQ里发送消息吗

**Comment by fanlu** [comment]
> 

对的

**Comment by Night-stars-1** [comment]
> 

最新版我这边测试是正常，没有用虚拟环境
<img width="616" alt="image" src="https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/99261160/f9d29f96-46af-4b90-8d89-f9ed399cc4d7">

**Comment by Ljzd-PRO** [comment]
> > 
> 
> 最新版我这边测试是正常，没有用虚拟环境 <img alt="image" width="616" src="https://user-images.githubusercontent.com/99261160/247935482-f9d29f96-46af-4b90-8d89-f9ed399cc4d7.png">

Windows吗？

**Comment by Night-stars-1** [comment]
> > > 
> > 
> > 
> > 最新版我这边测试是正常，没有用虚拟环境 <img alt="image" width="616" src="https://user-images.githubusercontent.com/99261160/247935482-f9d29f96-46af-4b90-8d89-f9ed399cc4d7.png">
> 
> Windows吗？

是的，定位到了，这个报错不是因为系统的原因

**Comment by Night-stars-1** [comment]
> > > 
> > 
> > 
> > 最新版我这边测试是正常，没有用虚拟环境 <img alt="image" width="616" src="https://user-images.githubusercontent.com/99261160/247935482-f9d29f96-46af-4b90-8d89-f9ed399cc4d7.png">
> 
> Windows吗？

已经修复了图片生成报错

**Comment by Ljzd-PRO** [comment]
新版本已发布：https://github.com/Ljzd-PRO/nonebot-plugin-mystool/releases/tag/v1.0.0
