### ISSUE TITLE
原神兑换原石失败

### ISSUE THREAD

**Issue by Sakamakiiizayoi** [Ljzd-PRO/nonebot-plugin-mystool#110]
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/67581432/c0cb23f5-d480-49a5-930a-5748eea33a95)
上次0.2.8也是这样 然后更新到了0.2.9也是报错

**Comment by Sakamakiiizayoi** [comment]
我去ubuntu上重新部署一个机器人试试

**Comment by Sakamakiiizayoi** [comment]
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/67581432/8e75714d-c5c9-41eb-8c18-bd3555a958a7)
新部署的机器人也不行 有没有和我一样的 是不是我这个号被ban了

**Comment by Ljzd-PRO** [comment]
https://github.com/Ljzd-PRO/Mys_Goods_Tool/issues/116 情况一样，只有原神的商品不行，可能和 `x-rpc-app_version` 有关，需要更新这个版本号，抓包发现原神和其他分区的兑换请求是一样的。

**Comment by Ljzd-PRO** [comment]
以及 https://github.com/Ljzd-PRO/Mys_Goods_Tool/issues/114

**Comment by Ljzd-PRO** [comment]
明天有一次兑换，如果需要兑换的话可以试试 [dev 分支的代码](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/archive/refs/heads/dev.zip)，这次修改的感觉成功率会大一些。或者使用：https://github.com/Ljzd-PRO/Mys_Goods_Tool/releases/tag/v2.1.0-beta.1

**Comment by Sakamakiiizayoi** [comment]
`07-12 16:24:33 [DEBUG] nonebot_plugin_mystool | 网络请求返回: {"data":null,"message":"invalid request","retcode":-10001}
07-12 16:24:33 [INFO] nonebot_plugin_mystool | success=False network_error=False incorrect_return=True login_expired=False need_verify=False invalid_ds=False no_genshin_account=False
07-12 17:24:33 [INFO] nonebot_plugin_mystool | 原神实时便笺: 用户 76430257 可能被验证码阻拦
07-12 17:24:33 [DEBUG] nonebot_plugin_mystool | 网络请求返回: {"data":null,"message":"","retcode":1034}
07-12 17:24:33 [ERROR] nonebot_plugin_mystool | 原神实时便笺: 服务器没有正确返回
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pydantic/main.py", line 522, in parse_obj
    obj = dict(obj)
TypeError: 'NoneType' object is not iterable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/nonebot_plugin_mystool/simple_api.py", line 1446, in genshin_board
    GenshinBoard.parse_obj(api_result.data)
  File "/usr/lib/python3.10/site-packages/pydantic/main.py", line 525, in parse_obj
    raise ValidationError([ErrorWrapper(exc, loc=ROOT_KEY)], cls) from e
pydantic.error_wrappers.ValidationError: 1 validation error for GenshinBoard
__root__
  GenshinBoard expected dict not NoneType (type=type_error)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/mybot/bot.py", line 22, in <module>
    nonebot.run()
  File "/usr/lib/python3.10/site-packages/nonebot/__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 198, in run
    uvicorn.run(
  File "/usr/lib/python3.10/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/usr/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
  File "/usr/lib/python3.10/asyncio/base_events.py", line 633, in run_until_complete
  File "/usr/lib/python3.10/asyncio/base_events.py", line 600, in run_forever
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1896, in _run_once
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
  File "/usr/lib/python3.10/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "/usr/lib/python3.10/site-packages/nonebot_plugin_mystool/plan.py", line 455, in auto_resin_check
    await resin_check(bot=bot, qq=qq, is_auto=True)
  File "/usr/lib/python3.10/site-packages/nonebot_plugin_mystool/plan.py", line 331, in resin_check
    genshin_board_status, board = await genshin_board(account)
> File "/usr/lib/python3.10/site-packages/nonebot_plugin_mystool/simple_api.py", line 1411, in genshin_board
    async for attempt in get_async_retry(False):
  File "/usr/lib/python3.10/site-packages/tenacity/_asyncio.py", line 71, in __anext__
    do = self.iter(retry_state=self._retry_state)
  File "/usr/lib/python3.10/site-packages/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x7f86c7b470 state=finished raised ValidationError>]
07-12 17:24:33 [DEBUG] nonebot_plugin_mystool | 网络请求返回: {"data":null,"message":"invalid request","retcode":-10001}
07-12 17:24:33 [INFO] nonebot_plugin_mystool | success=False network_error=False incorrect_return=True login_expired=False need_verify=False invalid_ds=False no_genshin_account=False
07-12 18:24:32 [INFO] nonebot_plugin_mystool | 原神实时便笺: 用户 76430257 可能被验证码阻拦
07-12 18:24:32 [DEBUG] nonebot_plugin_mystool | 网络请求返回: {"data":null,"message":"","retcode":1034}
07-12 18:24:33 [ERROR] nonebot_plugin_mystool | 原神实时便笺: 服务器没有正确返回
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pydantic/main.py", line 522, in parse_obj
    obj = dict(obj)
TypeError: 'NoneType' object is not iterable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/nonebot_plugin_mystool/simple_api.py", line 1446, in genshin_board
    GenshinBoard.parse_obj(api_result.data)
  File "/usr/lib/python3.10/site-packages/pydantic/main.py", line 525, in parse_obj
    raise ValidationError([ErrorWrapper(exc, loc=ROOT_KEY)], cls) from e
pydantic.error_wrappers.ValidationError: 1 validation error for GenshinBoard
__root__
  GenshinBoard expected dict not NoneType (type=type_error)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/mybot/bot.py", line 22, in <module>
    nonebot.run()
  File "/usr/lib/python3.10/site-packages/nonebot/__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 198, in run
    uvicorn.run(
  File "/usr/lib/python3.10/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/usr/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
  File "/usr/lib/python3.10/asyncio/base_events.py", line 633, in run_until_complete
  File "/usr/lib/python3.10/asyncio/base_events.py", line 600, in run_forever
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1896, in _run_once
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
  File "/usr/lib/python3.10/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "/usr/lib/python3.10/site-packages/nonebot_plugin_mystool/plan.py", line 455, in auto_resin_check
    await resin_check(bot=bot, qq=qq, is_auto=True)
  File "/usr/lib/python3.10/site-packages/nonebot_plugin_mystool/plan.py", line 331, in resin_check
    genshin_board_status, board = await genshin_board(account)
> File "/usr/lib/python3.10/site-packages/nonebot_plugin_mystool/simple_api.py", line 1411, in genshin_board
    async for attempt in get_async_retry(False):
  File "/usr/lib/python3.10/site-packages/tenacity/_asyncio.py", line 71, in __anext__
    do = self.iter(retry_state=self._retry_state)
  File "/usr/lib/python3.10/site-packages/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x7f86c1d2d0 state=finished raised ValidationError>]
07-12 18:24:33 [DEBUG] nonebot_plugin_mystool | 网络请求返回: {"data":null,"message":"invalid request","retcode":-10001}
07-12 18:24:33 [INFO] nonebot_plugin_mystool | success=False network_error=False incorrect_return=True login_expired=False need_verify=False invalid_ds=False no_genshin_account=False
07-12 19:00:00 [INFO] nonebot_plugin_mystool | 米游币商品兑换 - 执行兑换: 用户 76430257 商品 2023062912210 兑换失败，可以自行确认。
07-12 19:00:00 [DEBUG] nonebot_plugin_mystool | 网络请求返回: {"data":null,"message":"","retcode":1028}
07-12 19:00:00 [INFO] nonebot_plugin_mystool | 米游币商品兑换 - 执行兑换: 用户 76430257 商品 2023062912210 兑换失败，可以自行确认。
07-12 19:00:00 [DEBUG] nonebot_plugin_mystool | 网络请求返回: {"data":null,"message":"","retcode":1028}`

**Comment by Sakamakiiizayoi** [comment]
```python
07-12 17:24:33 [DEBUG] nonebot_plugin_mystool | 网络请求返回: {"data":null,"message":"invalid request","retcode":-10001}
07-12 17:24:33 [INFO] nonebot_plugin_mystool | success=False network_error=False incorrect_return=True login_expired=False need_verify=False invalid_ds=False no_genshin_account=False
07-12 18:24:32 [INFO] nonebot_plugin_mystool | 原神实时便笺: 用户 76430257 可能被验证码阻拦
07-12 18:24:32 [DEBUG] nonebot_plugin_mystool | 网络请求返回: {"data":null,"message":"","retcode":1034}
07-12 18:24:33 [ERROR] nonebot_plugin_mystool | 原神实时便笺: 服务器没有正确返回
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pydantic/main.py", line 522, in parse_obj
    obj = dict(obj)
TypeError: 'NoneType' object is not iterable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/nonebot_plugin_mystool/simple_api.py", line 1446, in genshin_board
    GenshinBoard.parse_obj(api_result.data)
  File "/usr/lib/python3.10/site-packages/pydantic/main.py", line 525, in parse_obj
    raise ValidationError([ErrorWrapper(exc, loc=ROOT_KEY)], cls) from e
pydantic.error_wrappers.ValidationError: 1 validation error for GenshinBoard
__root__
  GenshinBoard expected dict not NoneType (type=type_error)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/mybot/bot.py", line 22, in <module>
    nonebot.run()
  File "/usr/lib/python3.10/site-packages/nonebot/__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 198, in run
    uvicorn.run(
  File "/usr/lib/python3.10/site-packages/uvicorn/main.py", line 578, in run
    server.run()
  File "/usr/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
  File "/usr/lib/python3.10/asyncio/base_events.py", line 633, in run_until_complete
  File "/usr/lib/python3.10/asyncio/base_events.py", line 600, in run_forever
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1896, in _run_once
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
  File "/usr/lib/python3.10/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "/usr/lib/python3.10/site-packages/nonebot_plugin_mystool/plan.py", line 455, in auto_resin_check
    await resin_check(bot=bot, qq=qq, is_auto=True)
  File "/usr/lib/python3.10/site-packages/nonebot_plugin_mystool/plan.py", line 331, in resin_check
    genshin_board_status, board = await genshin_board(account)
> File "/usr/lib/python3.10/site-packages/nonebot_plugin_mystool/simple_api.py", line 1411, in genshin_board
    async for attempt in get_async_retry(False):
  File "/usr/lib/python3.10/site-packages/tenacity/_asyncio.py", line 71, in __anext__
    do = self.iter(retry_state=self._retry_state)
  File "/usr/lib/python3.10/site-packages/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x7f86c1d2d0 state=finished raised ValidationError>]
07-12 18:24:33 [DEBUG] nonebot_plugin_mystool | 网络请求返回: {"data":null,"message":"invalid request","retcode":-10001}
07-12 18:24:33 [INFO] nonebot_plugin_mystool | success=False network_error=False incorrect_return=True login_expired=False need_verify=False invalid_ds=False no_genshin_account=False
07-12 19:00:00 [INFO] nonebot_plugin_mystool | 米游币商品兑换 - 执行兑换: 用户 76430257 商品 2023062912210 兑换失败，可以自行确认。
07-12 19:00:00 [DEBUG] nonebot_plugin_mystool | 网络请求返回: {"data":null,"message":"","retcode":1028}
07-12 19:00:00 [INFO] nonebot_plugin_mystool | 米游币商品兑换 - 执行兑换: 用户 76430257 商品 2023062912210 兑换失败，可以自行确认。
07-12 19:00:00 [DEBUG] nonebot_plugin_mystool | 网络请求返回: {"data":null,"message":"","retcode":1028}
```

**Comment by Ljzd-PRO** [comment]
https://github.com/Ljzd-PRO/Mys_Goods_Tool/issues/132

原因是现在加了人机验证
