### ISSUE TITLE
poetry 虚拟环境下商品命令报错

### ISSUE THREAD

**Issue by xxtg666** [Ljzd-PRO/nonebot-plugin-mystool#118]
使用的机器人：https://github.com/Mar-7th/March7th

使用 `poetry run nb run --reload` 启动bot后，使用`商品`命令，发送对应的类别后，机器人会崩溃：
```log
06-20 13:30:07 [SUCCESS] nonebot | OneBot V11 337****446 | [message.private.friend]: Message -208391237 from 174****912 '#商品'
06-20 13:30:07 [DEBUG] nonebot | Running PreProcessors...
06-20 13:30:07 [DEBUG] nonebot | Checking for matchers in priority 1...
06-20 13:30:07 [DEBUG] nonebot | Checking for matchers in priority 2...
06-20 13:30:07 [DEBUG] nonebot | Checking for matchers in priority 4...
06-20 13:30:07 [DEBUG] nonebot | Checking for matchers in priority 5...
06-20 13:30:07 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_mystool.exchangePlan)
06-20 13:30:07 [DEBUG] nonebot | Running Matcher(type='message', module=nonebot_plugin_mystool.exchangePlan)
06-20 13:30:07 [DEBUG] nonebot | Running handler Dependent(call=_)
06-20 13:30:07 [DEBUG] nonebot | Running handler Dependent(call=_, parameterless=(Depends(Dependent(call=_key_getter)),))
06-20 13:30:07 [DEBUG] nonebot | OneBot V11 | Calling API send_msg
06-20 13:30:07 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_mystool.exchangePlan) running complete
06-20 13:30:07 [DEBUG] nonebot | Stop event propagation
06-20 13:30:07 [DEBUG] nonebot | Checking for matchers completed
06-20 13:30:09 [SUCCESS] nonebot | OneBot V11 337****446 | [message.private.friend]: Message -1587160868 from 174****912 '米游社'
06-20 13:30:09 [DEBUG] nonebot | Running PreProcessors...
06-20 13:30:09 [DEBUG] nonebot | Checking for matchers in priority 0...
06-20 13:30:09 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_mystool.exchangePlan)
06-20 13:30:09 [DEBUG] nonebot | Running Matcher(type='message', module=nonebot_plugin_mystool.exchangePlan)
06-20 13:30:09 [DEBUG] nonebot | Running handler Dependent(call=_, parameterless=(Depends(Dependent(call=_key_getter)),))
Process SpawnPoolWorker-3:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 114, in worker
    task = get()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\queues.py", line 367, in get
    return _ForkingPickler.loads(res)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\march7th-tOe-_jBX-py3.10\lib\site-packages\nonebot_plugin_mystool\__init__.py", line 40, in <module>
    from .data import create_files
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\march7th-tOe-_jBX-py3.10\lib\site-packages\nonebot_plugin_mystool\data.py", line 9, in <module>
    from .config import PATH
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\march7th-tOe-_jBX-py3.10\lib\site-packages\nonebot_plugin_mystool\config.py", line 24, in <module>
    driver = get_driver()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\march7th-tOe-_jBX-py3.10\lib\site-packages\nonebot\__init__.py", line 80, in get_driver
    raise ValueError("NoneBot has not been initialized.")
ValueError: NoneBot has not been initialized.
Process SpawnPoolWorker-2:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 114, in worker
    task = get()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\queues.py", line 367, in get
    return _ForkingPickler.loads(res)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\march7th-tOe-_jBX-py3.10\lib\site-packages\nonebot_plugin_mystool\__init__.py", line 40, in <module>
    from .data import create_files
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\march7th-tOe-_jBX-py3.10\lib\site-packages\nonebot_plugin_mystool\data.py", line 9, in <module>
    from .config import PATH
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\march7th-tOe-_jBX-py3.10\lib\site-packages\nonebot_plugin_mystool\config.py", line 24, in <module>
    driver = get_driver()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\march7th-tOe-_jBX-py3.10\lib\site-packages\nonebot\__init__.py", line 80, in get_driver
    raise ValueError("NoneBot has not been initialized.")
ValueError: NoneBot has not been initialized.
Process SpawnPoolWorker-4:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 114, in worker
    task = get()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\queues.py", line 367, in get
    return _ForkingPickler.loads(res)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\march7th-tOe-_jBX-py3.10\lib\site-packages\nonebot_plugin_mystool\__init__.py", line 40, in <module>
    from .data import create_files
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\march7th-tOe-_jBX-py3.10\lib\site-packages\nonebot_plugin_mystool\data.py", line 9, in <module>
    from .config import PATH
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\march7th-tOe-_jBX-py3.10\lib\site-packages\nonebot_plugin_mystool\config.py", line 24, in <module>
    driver = get_driver()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\march7th-tOe-_jBX-py3.10\lib\site-packages\nonebot\__init__.py", line 80, in get_driver
    raise ValueError("NoneBot has not been initialized.")
ValueError: NoneBot has not been initialized.
Process SpawnPoolWorker-5:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 114, in worker
    task = get()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\queues.py", line 367, in get
    return _ForkingPickler.loads(res)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\march7th-tOe-_jBX-py3.10\lib\site-packages\nonebot_plugin_mystool\__init__.py", line 40, in <module>
    from .data import create_files
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\march7th-tOe-_jBX-py3.10\lib\site-packages\nonebot_plugin_mystool\data.py", line 9, in <module>
    from .config import PATH
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\march7th-tOe-_jBX-py3.10\lib\site-packages\nonebot_plugin_mystool\config.py", line 24, in <module>
    driver = get_driver()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\march7th-tOe-_jBX-py3.10\lib\site-packages\nonebot\__init__.py", line 80, in get_driver
    raise ValueError("NoneBot has not been initialized.")
ValueError: NoneBot has not been initialized.
Process SpawnPoolWorker-7:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 114, in worker
    task = get()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\queues.py", line 367, in get
    return _ForkingPickler.loads(res)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\march7th-tOe-_jBX-py3.10\lib\site-packages\nonebot_plugin_mystool\__init__.py", line 40, in <module>
    from .data import create_files
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\march7th-tOe-_jBX-py3.10\lib\site-packages\nonebot_plugin_mystool\data.py", line 9, in <module>
    from .config import PATH
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\march7th-tOe-_jBX-py3.10\lib\site-packages\nonebot_plugin_mystool\config.py", line 24, in <module>
    driver = get_driver()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\march7th-tOe-_jBX-py3.10\lib\site-packages\nonebot\__init__.py", line 80, in get_driver
    raise ValueError("NoneBot has not been initialized.")
ValueError: NoneBot has not been initialized.
Process SpawnPoolWorker-6:
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 114, in worker
    task = get()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\multiprocessing\queues.py", line 367, in get
    return _ForkingPickler.loads(res)
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\march7th-tOe-_jBX-py3.10\lib\site-packages\nonebot_plugin_mystool\__init__.py", line 40, in <module>
    from .data import create_files
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\march7th-tOe-_jBX-py3.10\lib\site-packages\nonebot_plugin_mystool\data.py", line 9, in <module>
    from .config import PATH
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\march7th-tOe-_jBX-py3.10\lib\site-packages\nonebot_plugin_mystool\config.py", line 24, in <module>
    driver = get_driver()
  File "C:\Users\Administrator\AppData\Local\pypoetry\Cache\virtualenvs\march7th-tOe-_jBX-py3.10\lib\site-packages\nonebot\__init__.py", line 80, in get_driver
    raise ValueError("NoneBot has not been initialized.")
ValueError: NoneBot has not been initialized.
```

**Comment by Ljzd-PRO** [comment]
商品图片生成失败，与 #108 #114 情况相同，Windows、macOS下会出错，Linux可以正常运行，和多进程有关。
可以暂时使用 v0.2.8 版本，目前还没找到解决方案

**Comment by xxtg666** [comment]
v0.2.8好像有兑换时间差一个星期错误的问题吧

**Comment by Ljzd-PRO** [comment]
> v0.2.8好像有兑换时间差一个星期错误的问题吧

在 v0.2.8 基础上像 https://github.com/Ljzd-PRO/nonebot-plugin-mystool/commit/3adb84b346be2f39a725ac6bf434046b39151720 这样修改一行代码就可以解决

**Comment by xxtg666** [comment]
好，解决了，谢谢大佬

**Comment by Ljzd-PRO** [comment]
已修复：https://github.com/Ljzd-PRO/nonebot-plugin-mystool/releases/tag/v1.0.0
