### ISSUE TITLE
无法更新商品和登录，不知道哪里出问题

### ISSUE THREAD

**Issue by Fins03** [Ljzd-PRO/nonebot-plugin-mystool#162]
登录，输入手机号，然后
............................................
```
08-13 11:32:45 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_mystool.login) failed.
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "/root/my/.venv/lib/python3.10/site-packages/nonebot/__init__.py", line 333, in run
    get_driver().run(*args, **kwargs)
  File "/root/my/.venv/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 199, in run
    uvicorn.run(
  File "/root/my/.venv/lib/python3.10/site-packages/uvicorn/main.py", line 587, in run
    server.run()
  File "/root/my/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/root/my/.venv/lib/python3.10/site-packages/nonebot/message.py", line 467, in check_and_run_matcher
    await _run_matcher(
> File "/root/my/.venv/lib/python3.10/site-packages/nonebot/message.py", line 419, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/root/my/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 759, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/root/my/.venv/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 734, in simple_run
    await handler(
  File "/root/my/.venv/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/root/my/.venv/lib/python3.10/site-packages/nonebot_plugin_mystool/login.py", line 69, in _
    account_filter = filter(lambda x: x.phone_number == phone, _conf.users[event.get_user_id()].accounts.values())
KeyError:“QQ号”
```
商品更新
.......................
```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 966, in _bootstrap
    self._bootstrap_inner()
  File "/usr/local/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/root/my/.venv/lib/python3.10/site-packages/nonebot_plugin_mystool/exchange.py", line 519, in generate_image
    with Pool() as pool:
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 212, in __init__
    self._repopulate_pool()
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 303, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/local/lib/python3.10/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/local/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/lib/python3.10/multiprocessing/popen_fork.py", line 71, in _launch
    code = process_obj._bootstrap(parent_sentinel=child_r)
  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/root/my/.venv/lib/python3.10/site-packages/nonebot_plugin_mystool/exchange.py", line 479, in image_process
    good_list_status, good_list = loop.run_until_complete(get_good_list(game))
> File "/root/my/.venv/lib/python3.10/site-packages/nonebot_plugin_mystool/simple_api.py", line 634, in get_good_list
    async for attempt in get_async_retry(retry):
  File "/root/my/.venv/lib/python3.10/site-packages/tenacity/_asyncio.py", line 71, in __anext__
    do = self.iter(retry_state=self._retry_state)
  File "/root/my/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0xffffa037bf10 state=finished raised ConnectTimeout>]
08-13 11:34:16 [ERROR] nonebot_plugin_mystool | 获取 bh3 分区的商品列表失败，跳过该分区的商品图片生成
```

**Comment by Ljzd-PRO** [comment]
登录的问题可以换成v1.1.0试试。
更新商品的问题可能和网络有关，提示连接超时

**Comment by Fins03** [comment]
好的，谢谢

**Comment by Ljzd-PRO** [comment]
更新至最新版，就是 v1.2.3，应该就没问题了
