### ISSUE TITLE
米游社任务问题与自动任务问题

### ISSUE THREAD

**Issue by wei-la-ya** [Ljzd-PRO/nonebot-plugin-mystool#173]
此为报错信息
此为手动执行
![8dec5e4fe480e7f9d74bd9270a15dffb](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/142399519/b69e609a-2fce-43b1-acb7-a8131f4b85ef)
此为自动执行
![bca5ba422fc6614466676d255cb89b1f](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/142399519/09bedb0c-d2d5-4fd2-8dd9-627fcb1abdd5)

**Comment by Fins03** [comment]
同样遇到没法自动执行任务，一直查询被人机验证的便筏，但是我没开便筏通知，任务执行后也没有通知

```
08-19 07:45:04 [ERROR] apscheduler | Job "auto_resin_check (trigger: interval[1:00:00], next run at: 2023-08-19 08:44:53 CST)" raised an exception
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "/root/mhy/.venv/lib/python3.10/site-packages/nonebot/__init__.py", line 333, in run
    get_driver().run(*args, **kwargs)
  File "/root/mhy/.venv/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 199, in run
    uvicorn.run(
  File "/root/mhy/.venv/lib/python3.10/site-packages/uvicorn/main.py", line 587, in run
    server.run()
  File "/root/mhy/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
> File "/root/mhy/.venv/lib/python3.10/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "/root/mhy/.venv/lib/python3.10/site-packages/nonebot_plugin_mystool/plan.py", line 568, in auto_resin_check
    await resin_check_sr(user_id=qq)
  File "/root/mhy/.venv/lib/python3.10/site-packages/nonebot_plugin_mystool/plan.py", line 509, in resin_check_sr
    if has_checked[account.bbs_uid]['rogue_score']:
KeyError: 'rogue_score'
```

**Comment by dontdot** [comment]
```
KeyError: 'rogue_score'
```
这个问题我遇到过，可以看看这个回答https://github.com/Ljzd-PRO/nonebot-plugin-mystool/issues/152#issuecomment-1681441889
这是我添加/修改的部分

https://github.com/Joseandluue/nonebot-plugin-mystool/blob/efd1859871468e35e9a1bb54574b5fd45269388e/src/nonebot_plugin_mystool/plan.py#L104-L112

https://github.com/Joseandluue/nonebot-plugin-mystool/blob/efd1859871468e35e9a1bb54574b5fd45269388e/src/nonebot_plugin_mystool/plan.py#L435-L489
