### ISSUE TITLE
发送登录命令报错

### ISSUE THREAD

**Issue by SiberianHuskyy** [Ljzd-PRO/nonebot-plugin-mystool#193]
09-11 15:11:52 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_mystool.login, lineno=25)
09-11 15:11:53 [ERROR] nonebot_plugin_mystool | 发送包含URL链接的登录消息失败
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "/root/ys/.venv/lib/python3.9/site-packages/nonebot/__init__.py", line 331, in run
    get_driver().run(*args, **kwargs)
  File "/root/ys/.venv/lib/python3.9/site-packages/nonebot/drivers/none.py", line 70, in run
    loop.run_until_complete(self._serve())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1890, in _run_once
    handle._run()
  File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/root/ys/.venv/lib/python3.9/site-packages/nonebot/message.py", line 467, in check_and_run_matcher
    await _run_matcher(
  File "/root/ys/.venv/lib/python3.9/site-packages/nonebot/message.py", line 419, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/root/ys/.venv/lib/python3.9/site-packages/nonebot/internal/matcher/matcher.py", line 846, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/root/ys/.venv/lib/python3.9/site-packages/nonebot/internal/matcher/matcher.py", line 821, in simple_run
    await handler(
  File "/root/ys/.venv/lib/python3.9/site-packages/nonebot/dependencies/__init__.py", line 113, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
> File "/root/ys/.venv/lib/python3.9/site-packages/nonebot_plugin_mystool/login.py", line 50, in handle_first_receive
    await get_cookie.send(msg_text.format(browse_way=f"前往 {login_url}"))
  File "/root/ys/.venv/lib/python3.9/site-packages/nonebot/internal/matcher/matcher.py", line 554, in send
    return await bot.send(event=event, message=_message, **kwargs)
  File "/root/ys/.venv/lib/python3.9/site-packages/nonebot/adapters/qqguild/bot.py", line 203, in send
    return await self.send_to_dms(
  File "/root/ys/.venv/lib/python3.9/site-packages/nonebot/adapters/qqguild/bot.py", line 172, in send_to_dms
    return await self.post_dms_messages(
  File "/root/ys/.venv/lib/python3.9/site-packages/nonebot/internal/adapter/bot.py", line 120, in call_api
    raise exception
  File "/root/ys/.venv/lib/python3.9/site-packages/nonebot/internal/adapter/bot.py", line 98, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "/root/ys/.venv/lib/python3.9/site-packages/nonebot/adapters/qqguild/adapter.py", line 377, in _call_api
    return await api_handler(self, bot, **data)
  File "/root/ys/.venv/lib/python3.9/site-packages/nonebot/adapters/qqguild/api/handle.py", line 315, in _post_dms_messages
    return parse_obj_as(Message, await _request(adapter, bot, request))
  File "/root/ys/.venv/lib/python3.9/site-packages/nonebot/adapters/qqguild/api/request.py", line 45, in _request
    raise ActionFailed(data)
nonebot.adapters.qqguild.exception.ActionFailed: <ActionFailed: 403, code=304003, message=url not allowed, data=None>
``
![QQ截图20230911231855](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/90309491/ae2a1c97-bc67-42aa-a031-c0889b55b8a5)

**Comment by Ljzd-PRO** [comment]
QQ频道机器人发送URL需要在开发者管理页面提前报备，所以默认会出现URL发送失败的情况。
不过也不影响使用，URL发送失败的话，会自动发送二维码，扫描二维码也可进入页面，二维码夜发送失败的话，就要自行搜索米哈游通行证登录页了。

**Comment by SiberianHuskyy** [comment]
启动插件报错能解决吗
![QQ截图20230912031144](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/90309491/791797bc-ea37-4051-b24c-3b974c21d391)
![QQ截图20230912031158](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/90309491/04e5b5c4-5296-4f98-b615-6c867e4de84a)

**Comment by Ljzd-PRO** [comment]
ARM设备吗？可能是pip安装Pillow的时候没有正确编译。

修改机器人目录下 `.venv/pyvenv.cfg` 虚拟环境配置文件，把 `include-system-site-packages` 设为 `true`，就是开启从系统继承包。
然后手动进入虚拟环境，卸载Pillow。
```
source <.venv目录路径>/bin/activate
```
```
pip uninstall pillow
```

用opkg安装编译好的python Pillow包，可以用命令安装，或者直接在路由器管理页面WebUI安装。或者自己编译固件的时候，在配置中加上这个包。
```
opkg install python3-pillow
```
最后启动机器人看看还有没有问题
