### ISSUE TITLE
昨天兑换失败，状态码1028

### ISSUE THREAD

**Issue by GhostarDragon** [Ljzd-PRO/nonebot-plugin-mystool#197]
顺便问一句，私聊消息也失败了

09-20 19:00:00 [INFO] nonebot_plugin_mystool | 米游币商品兑换: 用户 ********商品 2023080811214 兑换失败，可以自行确认 - 请求发送时间: 1695207600.0073936
09-20 19:00:00 [DEBUG] nonebot_plugin_mystool | 网络请求返回: {"data":null,"message":"","retcode":1028}
09-20 19:00:00 [INFO] nonebot_plugin_mystool | 米游币商品兑换: 用户 ********商品 2023080811214 兑换失败，可以自行确认 - 请求发送时间: 1695207600.0087204
09-20 19:00:00 [DEBUG] nonebot_plugin_mystool | 网络请求返回: {"data":null,"message":"","retcode":1028}
09-20 19:00:01 [ERROR] nonebot_plugin_mystool | QQGuild 尝试主动发送私信消息失败。频道ID：********，用户ID：********，消息内容：
💦账户 ********
- 【原神】提瓦特动物园主题系列 毛绒团子-八重神子
- 线程 2
- 兑换失败
Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "/root/taibu/.venv/lib/python3.10/site-packages/nonebot/__init__.py", line 331, in run
    get_driver().run(*args, **kwargs)
  File "/root/taibu/.venv/lib/python3.10/site-packages/nonebot/drivers/none.py", line 70, in run
    loop.run_until_complete(self._serve())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "/root/taibu/.venv/lib/python3.10/site-packages/nonebot_plugin_mystool/utils.py", line 415, in send_private_msg
    dms: DMS = await bot.post_dms(recipient_id=user_id, source_guild_id=guild_id)
  File "/root/taibu/.venv/lib/python3.10/site-packages/nonebot/internal/adapter/bot.py", line 120, in call_api
    raise exception
  File "/root/taibu/.venv/lib/python3.10/site-packages/nonebot/internal/adapter/bot.py", line 98, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "/root/taibu/.venv/lib/python3.10/site-packages/nonebot/adapters/qqguild/adapter.py", line 377, in _call_api
    return await api_handler(self, bot, **data)
  File "/root/taibu/.venv/lib/python3.10/site-packages/nonebot/adapters/qqguild/api/handle.py", line 302, in _post_dms
    return parse_obj_as(DMS, await _request(adapter, bot, request))
  File "/root/taibu/.venv/lib/python3.10/site-packages/nonebot/adapters/qqguild/api/request.py", line 45, in _request
    raise ActionFailed(data)
nonebot.adapters.qqguild.exception.ActionFailed: <ActionFailed: 500, code=305001, message=backend error, data=None>
09-20 19:00:01 [ERROR] nonebot_plugin_mystool | QQGuild 尝试主动发送私信消息失败。频道ID：********，用户ID：********，消息内容：
💦账户 ********
- 【原神】提瓦特动物园主题系列 毛绒团子-八重神子
- 线程 1
- 兑换失败
Traceback (most recent call last):
  File "<string>", line 15, in <module>
  File "/root/taibu/.venv/lib/python3.10/site-packages/nonebot/__init__.py", line 331, in run
    get_driver().run(*args, **kwargs)
  File "/root/taibu/.venv/lib/python3.10/site-packages/nonebot/drivers/none.py", line 70, in run
    loop.run_until_complete(self._serve())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "/root/taibu/.venv/lib/python3.10/site-packages/nonebot_plugin_mystool/utils.py", line 415, in send_private_msg
    dms: DMS = await bot.post_dms(recipient_id=user_id, source_guild_id=guild_id)
  File "/root/taibu/.venv/lib/python3.10/site-packages/nonebot/internal/adapter/bot.py", line 120, in call_api
    raise exception
  File "/root/taibu/.venv/lib/python3.10/site-packages/nonebot/internal/adapter/bot.py", line 98, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "/root/taibu/.venv/lib/python3.10/site-packages/nonebot/adapters/qqguild/adapter.py", line 377, in _call_api
    return await api_handler(self, bot, **data)
  File "/root/taibu/.venv/lib/python3.10/site-packages/nonebot/adapters/qqguild/api/handle.py", line 302, in _post_dms
    return parse_obj_as(DMS, await _request(adapter, bot, request))
  File "/root/taibu/.venv/lib/python3.10/site-packages/nonebot/adapters/qqguild/api/request.py", line 45, in _request
    raise ActionFailed(data)
nonebot.adapters.qqguild.exception.ActionFailed: <ActionFailed: 500, code=305001, message=backend error, data=None>
09-20 19:16:22 [INFO] nonebot_plugin_mystool | 开始执行自动便笺检查
09-20 19:16:22 [INFO] nonebot_plugin_mystool | 自动便笺检查执行完成
09-20 20:16:22 [INFO] nonebot_plugin_mystool | 开始执行自动便笺检查
09-20 20:16:22 [INFO] nonebot_plugin_mystool | 自动便笺检查执行完成
09-20 21:16:22 [INFO] nonebot_plugin_mystool | 开始执行自动便笺检查
09-20 21:16:22 [INFO] nonebot_plugin_mystool | 自动便笺检查执行完成
09-20 22:16:22 [INFO] nonebot_plugin_mystool | 开始执行自动便笺检查

**Comment by Ljzd-PRO** [comment]
原神和星铁的不好兑换，其他的可能可以
