### ISSUE TITLE
加载插件时报错

### ISSUE THREAD

**Issue by YuYue-Amatsuki** [Ljzd-PRO/nonebot-plugin-mystool#206]
```Python
11-01 17:41:09 [ERROR] uvicorn | Traceback (most recent call last):
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\drivers\fastapi.py", line 168, in _lifespan_manager
    await self._lifespan.startup()
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\drivers\_lifespan.py", line 36, in startup
    await self._run_lifespan_func(self._startup_funcs)
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\drivers\_lifespan.py", line 30, in _run_lifespan_fu
nc
    await cast(ASYNC_LIFESPAN_FUNC, func)()
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_mystool\exchange.py", line 470, in _
    run_date=datetime.fromtimestamp(good.time),
TypeError: 'NoneType' object cannot be interpreted as an integer
```

**Comment by Ljzd-PRO** [comment]
#205
