### ISSUE TITLE
QQ频道每日任务结果通知发送失败

### ISSUE THREAD

**Issue by WangQueXL** [Ljzd-PRO/nonebot-plugin-mystool#215]
QQ频道每日任务结果通知发送失败，在安装1.4.0时已经对Nonebot进行了全新安装，以及重新通过验证码绑定了账号数据

![{9535165B-94C7-49ba-A8AA-74133988BE4B}](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/95076858/96a85d35-a034-4894-8e2b-b7edabfe4fbf)

**Comment by Ljzd-PRO** [comment]
不太清楚，QQ官方的频道机器人文档里没有305001这个错误码。
看起来应该和主动私信发送有关。可以试试先主动给机器人私信发一条消息，然后在频道里使用`/私信响应`这个命令，机器人会用主动私信的方式给你发一条消息，同时保存群组ID之类的必要信息。如果这个也不行的话，应该就是别的原因了。

**Comment by Ljzd-PRO** [comment]
之前如果主动私信的时间太晚也可能会被拒绝，比如凌晨，但不是这个报错

**Comment by Ljzd-PRO** [comment]
顺便可以点开机器人详情页，设置私信推送上限，最高可以设置为50条。
另外如果没有给机器人私信发送过任何消息，机器人最多只能主动私信3次

**Comment by WangQueXL** [comment]
> 不太清楚，QQ官方的频道机器人文档里没有305001这个错误码。 看起来应该和主动私信发送有关。可以试试先主动给机器人私信发一条消息，然后在频道里使用`/私信响应`这个命令，机器人会用主动私信的方式给你发一条消息，同时保存群组ID之类的必要信息。如果这个也不行的话，应该就是别的原因了。

我这边之前在私信里面绑定好信息之后，第二天发现没有消息推送，在子频道里面尝试发过/私信响应，机器人也正常私信回复了响应，查看生成的配置文件也确实有频道的相关信息，但是很遗憾还是没有办法正常发出每日任务的私信推送，关于私信推送上限这个我之前已经手动设置过50条，我刚刚也去看也还是50条，0-6点这个时间段机器人不能发送主动消息所以我特地设置了早上7点

![{7BAA0599-199A-469a-9A56-DEAD71030A59}](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/95076858/17282af7-a2cc-44df-b345-d5280e782850)

![a87d93bd7549417270bab03025ab1e13](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/95076858/555abd25-3892-4326-b7d3-4354a0691eac)

**Comment by WangQueXL** [comment]
> 不太清楚，QQ官方的频道机器人文档里没有305001这个错误码。 看起来应该和主动私信发送有关。可以试试先主动给机器人私信发一条消息，然后在频道里使用`/私信响应`这个命令，机器人会用主动私信的方式给你发一条消息，同时保存群组ID之类的必要信息。如果这个也不行的话，应该就是别的原因了。

```
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "/root/桌面/NewMysTool/NewMysTool/.venv/lib/python3.10/site-packages/nonebot/__init__.py", line 331, in run
    get_driver().run(*args, **kwargs)
  File "/root/桌面/NewMysTool/NewMysTool/.venv/lib/python3.10/site-packages/nonebot/drivers/none.py", line 70, in run
    loop.run_until_complete(self._serve())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 600, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1896, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/root/桌面/NewMysTool/NewMysTool/.venv/lib/python3.10/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "/root/桌面/NewMysTool/NewMysTool/.venv/lib/python3.10/site-packages/nonebot_plugin_mystool/plan.py", line 612, in daily_schedule
    await perform_bbs_sign(user=user, user_ids=user_ids)
  File "/root/桌面/NewMysTool/NewMysTool/.venv/lib/python3.10/site-packages/nonebot_plugin_mystool/plan.py", line 413, in perform_bbs_sign
    await send_private_msg(user_id=user_id, message=msg)
> File "/root/桌面/NewMysTool/NewMysTool/.venv/lib/python3.10/site-packages/nonebot_plugin_mystool/utils.py", line 417, in send_private_msg
    dms: DMS = await bot.post_dms(recipient_id=user_id, source_guild_id=guild_id)
  File "/root/桌面/NewMysTool/NewMysTool/.venv/lib/python3.10/site-packages/nonebot/internal/adapter/bot.py", line 123, in call_api
    raise exception
  File "/root/桌面/NewMysTool/NewMysTool/.venv/lib/python3.10/site-packages/nonebot/internal/adapter/bot.py", line 98, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "/root/桌面/NewMysTool/NewMysTool/.venv/lib/python3.10/site-packages/nonebot/adapters/qq/adapter.py", line 416, in _call_api
    return await api_handler(bot, **data)
  File "/root/桌面/NewMysTool/NewMysTool/.venv/lib/python3.10/site-packages/nonebot/adapters/qq/utils.py", line 64, in __call__
    return await self.func(inst, *args, **kwds)
  File "/root/桌面/NewMysTool/NewMysTool/.venv/lib/python3.10/site-packages/nonebot/adapters/qq/bot.py", line 957, in post_dms
    return parse_obj_as(DMS, await self._request(request))
  File "/root/桌面/NewMysTool/NewMysTool/.venv/lib/python3.10/site-packages/nonebot/adapters/qq/bot.py", line 466, in _request
    return self._handle_response(response)
  File "/root/桌面/NewMysTool/NewMysTool/.venv/lib/python3.10/site-packages/nonebot/adapters/qq/bot.py", line 455, in _handle_response
    raise ActionFailed(response)
nonebot.adapters.qq.exception.ActionFailed: <ActionFailed: 500, code=305001, message=backend error, trace_id=34b03f850361da775a310e212213062c>
```

**Comment by WangQueXL** [comment]
> 不太清楚，QQ官方的频道机器人文档里没有305001这个错误码。 看起来应该和主动私信发送有关。可以试试先主动给机器人私信发一条消息，然后在频道里使用`/私信响应`这个命令，机器人会用主动私信的方式给你发一条消息，同时保存群组ID之类的必要信息。如果这个也不行的话，应该就是别的原因了。

看来可能是adapter-qq的问题，更新了前两天发布1.1.2版本适配器，推送正常了
