### ISSUE TITLE
原神便笺出错了

### ISSUE THREAD

**Issue by dontdot** [Ljzd-PRO/nonebot-plugin-mystool#216]
昨天开始的，截至昨天为止用了两个月都没问题
是否是api变了？
log：
<details><summary>Details</summary>
<p>
11-19 14:35:24 [ERROR] nonebot_plugin_mystool | 原神实时便笺: 服务器没有正确返回
Traceback (most recent call last):
  File "pydantic\main.py", line 522, in pydantic.main.BaseModel.parse_obj
    obj = dict(obj)
TypeError: 'NoneType' object is not iterable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\3y7\Lib\site-packages\nonebot_plugin_mystool\simple_api.py", line 1525, in genshin_note
    return GenshinNoteStatus(success=True), GenshinNote.parse_obj(api_result.data)
  File "pydantic\main.py", line 525, in pydantic.main.BaseModel.parse_obj
    raise ValidationError([ErrorWrapper(exc, loc=ROOT_KEY)], cls) from e
pydantic.error_wrappers.ValidationError: 1 validation error for GenshinNote
__root__
  GenshinNote expected dict not NoneType (type=type_error)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 19, in <module>
  File "C:\ProgramData\anaconda3\envs\3y7\Lib\site-packages\nonebot\__init__.py", line 309, in run
    get_driver().run(*args, **kwargs)
  File "C:\ProgramData\anaconda3\envs\3y7\Lib\site-packages\nonebot\drivers\fastapi.py", line 198, in run
    uvicorn.run(
  File "C:\ProgramData\anaconda3\envs\3y7\Lib\site-packages\uvicorn\main.py", line 578, in run
    server.run()
  File "C:\ProgramData\anaconda3\envs\3y7\Lib\site-packages\uvicorn\server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\ProgramData\anaconda3\envs\3y7\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\ProgramData\anaconda3\envs\3y7\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\ProgramData\anaconda3\envs\3y7\Lib\asyncio\base_events.py", line 640, in run_until_complete
    self.run_forever()
  File "C:\ProgramData\anaconda3\envs\3y7\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\ProgramData\anaconda3\envs\3y7\Lib\asyncio\base_events.py", line 607, in run_forever
    self._run_once()
  File "C:\ProgramData\anaconda3\envs\3y7\Lib\asyncio\base_events.py", line 1922, in _run_once
    handle._run()
  File "C:\ProgramData\anaconda3\envs\3y7\Lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\ProgramData\anaconda3\envs\3y7\Lib\site-packages\apscheduler\executors\base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "C:\ProgramData\anaconda3\envs\3y7\Lib\site-packages\nonebot_plugin_mystool\plan.py", line 634, in auto_note_check
    await genshin_note_check(user=user, user_ids=user_ids)
  File "C:\ProgramData\anaconda3\envs\3y7\Lib\site-packages\nonebot_plugin_mystool\plan.py", line 433, in genshin_note_check
    genshin_board_status, note = await genshin_note(account)
> File "C:\ProgramData\anaconda3\envs\3y7\Lib\site-packages\nonebot_plugin_mystool\simple_api.py", line 1484, in genshin_note
    async for attempt in get_async_retry(False):
  File "C:\ProgramData\anaconda3\envs\3y7\Lib\site-packages\tenacity\_asyncio.py", line 71, in __anext__
    do = self.iter(retry_state=self._retry_state)
  File "C:\ProgramData\anaconda3\envs\3y7\Lib\site-packages\tenacity\__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x1474881dd10 state=finished raised ValidationError>]
11-19 14:35:24 [DEBUG] nonebot_plugin_mystool | 网络请求返回: {"data":null,"message":"","retcode":5003}
</p>
</details>

**Comment by Ljzd-PRO** [comment]
重新登录也一样吗？5003好像是没见过

**Comment by dontdot** [comment]
> 重新登录也一样吗？5003好像是没见过

是的，签到，米游币，铁道便笺都可以，只有原神便笺不行
补充一下日志截图
![a1012868ade39dc49159b321ebc13b5a](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/55482264/0fcf61de-014d-491c-a592-096731d116ed)
