### ISSUE TITLE
点赞任务失败-“请补充个人信息”

### ISSUE THREAD

**Issue by ytgo** [Ljzd-PRO/nonebot-plugin-mystool#24]
米游币任务 - 点赞: 服务器没有正确返回

**Comment by Ljzd-PRO** [comment]
看一下详细的日志，在NoneBot控制台，或者机器人目录下的 data/nonebot-plugin-mystool/mystool.log

**Comment by ytgo** [comment]
米游币任务 - 点赞: 服务器没有正确返回
09-07 21:57:36 [DEBUG] nonebot_plugin_mystool | 网络请求返回: {"data":null,"message":"请补充个人信息","retcode":-200}
09-07 21:57:36 [DEBUG] nonebot_plugin_mystool | Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/nonebot_plugin_mystool/mybMission.py", line 298, in like
    async for attempt in tenacity.AsyncRetrying(stop=custom_attempt_times(retry), reraise=True, wait=tenacity.wait_fixed(conf.SLEEP_TIME_RETRY)):
  File "/usr/local/lib/python3.9/dist-packages/tenacity/_asyncio.py", line 69, in __anext__
    do = self.iter(retry_state=self._retry_state)
  File "/usr/local/lib/python3.9/dist-packages/tenacity/__init__.py", line 360, in iter
    raise retry_exc.reraise()
  File "/usr/local/lib/python3.9/dist-packages/tenacity/__init__.py", line 193, in reraise
    raise self.last_attempt.result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 433, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.9/dist-packages/nonebot_plugin_mystool/mybMission.py", line 310, in like
    raise ValueError                                                                            ValueError

**Comment by Ljzd-PRO** [comment]
有用机器人登录绑定过是吗

**Comment by Ljzd-PRO** [comment]
如果是新号的话，要先下载米游社App完成新号的一些操作才行
