### ISSUE TITLE
设置兑换后，查询兑换里面没有兑换计划

### ISSUE THREAD

**Issue by laurelcafe** [Ljzd-PRO/nonebot-plugin-mystool#26]
发送想要接收奖励的账号UID后机器人没有反应，然后查询兑换里面显示里面没有兑换计划

**Comment by Everything0519** [comment]
可以的话打开log看下报错 我们自己测试没问题的

**Comment by laurelcafe** [comment]
AttributeError: 'NoneType' object has no attribute 'addressID'
有一句这个报错，是什么原因啊

**Comment by laurelcafe** [comment]
09-13 22:59:56 [ERROR] nonebot | Running matcher <Matcher from nonebot_plugin_mystool.exchangePlan, type=message, priority=0, temp=True> failed.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/usr/lib/python3.10/multiprocessing/spawn.py", line 129, in _main
    return self._bootstrap(parent_sentinel)
  File "/usr/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/usr/local/lib/python3.10/dist-packages/nonebot/message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/internal/matcher.py", line 672, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/usr/local/lib/python3.10/dist-packages/nonebot/internal/matcher.py", line 639, in simple_run
    await handler(
  File "/usr/local/lib/python3.10/dist-packages/nonebot/dependencies/__init__.py", line 92, in __call__
    return await self.call(**values)
  File "/usr/local/lib/python3.10/dist-packages/nonebot_plugin_mystool/exchangePlan.py", line 258, in _
    exchange_plan = await Exchange(account, good.goodID, uid).async_init()
  File "/usr/local/lib/python3.10/dist-packages/nonebot_plugin_mystool/exchange.py", line 319, in async_init
    "address_id": self.account.address.addressID
AttributeError: 'NoneType' object has no attribute 'addressID'
09-13 22:59:56 [DEBUG] nonebot | Stop event propagation

**Comment by Everything0519** [comment]
稍等 我研究一下

**Comment by laurelcafe** [comment]
好的，麻烦了

**Comment by Everything0519** [comment]
这个问题应该已经修复了 在dev测试版里 但是还没有正常发行

**Comment by laurelcafe** [comment]
好的，了解

**Comment by Everything0519** [comment]
可以的话你直接复制exchange.py里面的代码 替换一下 应该就可以了 测试版现在还有其他bug

**Comment by laurelcafe** [comment]
多谢，问题解决了

**Comment by Everything0519** [comment]
没事儿没事儿

**Comment by laurelcafe** [comment]
好像没解决，会提示获取商品 2022082312197 的信息时，网络连接失败或服务器返回不正确，放弃兑换

??????? - ???????: ???? 2022082312197 ?????
09-13 23:37:48 [DEBUG] nonebot_plugin_mystool | ??????: {"retcode":0,"message":"OK","data":{"app_id":1,"goods_id":"2022082312197","goods_name":"??????*120","goods_desc":"","goods_detail":"\u003cp\u003e\u003cstrong\u003e????\u003c/strong\u003e???*120\u003cstrong\u003e?3.0??????\u003c/strong\u003e\u003c/p\u003e\n\n\u003cp line=\"WmSI\"\u003e\u003cstrong\u003e????\u003c/strong\u003e???? - ????????3????????????20?\u003c/p\u003e\n\n\u003cp line=\"z8EX\"\u003e\u003cstrong\u003e????\u003c/strong\u003e??????????????????~??????????\u003c/p\u003e\n\n\u003cp line=\"z8EX\"\u003e\u003cstrong\u003e????\u003c/strong\u003e?????????????????????????????30????????????????????????????????????\u003c/p\u003e\n","icon":"https://webstatic.mihoyo.com/upload/shop/2021/10/20/dab394b1516c58a00b91f8dba9756110_8904801501338765557.png","type":2,"price":3600,"cover":[{"type":"","url":"https://webstatic.mihoyo.com/upload/shop/2021/10/20/dab394b1516c58a00b91f8dba9756110_8904801501338765557.png"}],"point_sn":"myb","unlimit":false,"total":0,"account_cycle_type":"forever","account_cycle_limit":1,"account_exchange_num":0,"role_cycle_type":"not_limit","role_cycle_limit":0,"role_exchange_num":0,"rules":[{"rule_id":1,"values":["2:3"]},{"rule_id":2,"values":["20"]}],"game":"hk4e","game_biz":"hk4e_cn","start":"1661529600","end":"1664294400","status":"online","bbs_detail":[],"next_time":1663758000,"sale_start_time":"1662548400","next_num":1500,"now_time":1663083468,"jump_url":""}}
09-13 23:37:48 [DEBUG] nonebot_plugin_mystool | Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nonebot_plugin_mystool/exchange.py", line 334, in async_init
    self.content.pop("address_id")
KeyError: 'address_id'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/nonebot_plugin_mystool/exchange.py", line 327, in async_init
    async for attempt in tenacity.AsyncRetrying(stop=custom_attempt_times(retry), wait=tenacity.wait_fixed(conf.SLEEP_TIME_RETRY)):
  File "/usr/local/lib/python3.10/dist-packages/tenacity/_asyncio.py", line 69, in __anext__
    do = self.iter(retry_state=self._retry_state)
  File "/usr/local/lib/python3.10/dist-packages/tenacity/__init__.py", line 361, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x700d031000 state=finished raised KeyError>]

09-13 23:37:48 [DEBUG] nonebot | OneBot V11 | Calling API send_msg
09-13 23:37:48 [INFO] nonebot | Matcher <Matcher from nonebot_plugin_mystool.exchangePlan, type=message, priority=0, temp=True> running complete
09-13 23:37:48 [DEBUG] nonebot | Stop event propagat

**Comment by laurelcafe** [comment]
这次倒是没报错，是虚拟商品不能提前设置吗？

**Comment by laurelcafe** [comment]
找到问题了，要先设置地址ID才行

**Comment by Everything0519** [comment]
是的 但是我们之前修复了 兑换类似于原石的虚拟商品 不需要addressid了 看起来是我们没修复成功 我现在再去看一下问题在哪儿
按理来说 只有实体商品才需要地址id

**Comment by Everything0519** [comment]
现在在dev里提交了新代码 应该已经解决了

**Comment by laurelcafe** [comment]
想问下想改自动签到和任务的时间是从哪里改

**Comment by Everything0519** [comment]
config.py config类 后续会改成代码外json形式
