### ISSUE TITLE
OnebotV11 QQ频道机器人，登录通过短信验证码获取 login_ticket: 网络请求失败

### ISSUE THREAD

**Issue by Siiika-latest** [Ljzd-PRO/nonebot-plugin-mystool#263]
按照私聊频道机器人登录-输入手机号-扫码-获取验证码-发送给bot的流程。

以下是日志信息

```
02-26 14:18:24 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_mystool.command.login, lineno=23)
02-26 14:18:40 [ERROR] nonebot_plugin_mystool | 通过短信验证码获取 login_ticket: 网络请求失败
Traceback (most recent call last):
  File "/root/bot/mihoyobot/.venv/lib/python3.11/site-packages/nonebot_plugin_mystool/api/common.py", line 939, in get_login_ticket_by_captcha
    res = await request()
  File "/root/bot/mihoyobot/.venv/lib/python3.11/site-packages/nonebot_plugin_mystool/api/common.py", line 929, in request
    return await client.post(URL_LOGIN_TICKET_BY_CAPTCHA,
  File "/root/bot/mihoyobot/.venv/lib/python3.11/site-packages/httpx/_client.py", line 1877, in post
    return await self.request(
  File "/root/bot/mihoyobot/.venv/lib/python3.11/site-packages/httpx/_client.py", line 1559, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/root/bot/mihoyobot/.venv/lib/python3.11/site-packages/httpx/_client.py", line 1635, in send
    raise RuntimeError("Cannot send a request, as the client has been closed.")
RuntimeError: Cannot send a request, as the client has been closed.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/bot/mihoyobot/bot.py", line 46, in <module>
    nonebot.run()
  File "/root/bot/mihoyobot/.venv/lib/python3.11/site-packages/nonebot/__init__.py", line 334, in run
    get_driver().run(*args, **kwargs)
  File "/root/bot/mihoyobot/.venv/lib/python3.11/site-packages/nonebot/drivers/fastapi.py", line 186, in run
    uvicorn.run(
  File "/root/bot/mihoyobot/.venv/lib/python3.11/site-packages/uvicorn/main.py", line 587, in run
    server.run()
  File "/root/bot/mihoyobot/.venv/lib/python3.11/site-packages/uvicorn/server.py", line 62, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/root/.pyenv/versions/3.11.8/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
  File "/root/.pyenv/versions/3.11.8/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "/root/bot/mihoyobot/.venv/lib/python3.11/site-packages/nonebot/message.py", line 476, in check_and_run_matcher
    await _run_matcher(
  File "/root/bot/mihoyobot/.venv/lib/python3.11/site-packages/nonebot/message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/root/bot/mihoyobot/.venv/lib/python3.11/site-packages/nonebot/internal/matcher/matcher.py", line 842, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/root/bot/mihoyobot/.venv/lib/python3.11/site-packages/nonebot/internal/matcher/matcher.py", line 817, in simple_run
    await handler(
  File "/root/bot/mihoyobot/.venv/lib/python3.11/site-packages/nonebot/dependencies/__init__.py", line 106, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/root/bot/mihoyobot/.venv/lib/python3.11/site-packages/nonebot_plugin_mystool/command/login.py", line 137, in _
    login_status, cookies = await get_login_ticket_by_captcha(phone_number, int(captcha), device_id)
> File "/root/bot/mihoyobot/.venv/lib/python3.11/site-packages/nonebot_plugin_mystool/api/common.py", line 936, in get_login_ticket_by_captcha
    async for attempt in get_async_retry(retry):
  File "/root/bot/mihoyobot/.venv/lib/python3.11/site-packages/tenacity/_asyncio.py", line 71, in __anext__
    do = self.iter(retry_state=self._retry_state)
  File "/root/bot/mihoyobot/.venv/lib/python3.11/site-packages/tenacity/__init__.py", line 326, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x7f0db8867b50 state=finished raised RuntimeError>]
02-26 14:18:41 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_mystool.command.login, lineno=23) running complete
```

**Comment by Ljzd-PRO** [comment]
> RuntimeError: Cannot send a request, as the client has been closed.

看上去确实是网络问题

**Comment by Siiika-latest** [comment]
切换到了大陆服务器，正常了）小心香港服务器骗局
