### ISSUE TITLE
启动失败，求大佬指导

### ISSUE THREAD

**Issue by VAHua** [Ljzd-PRO/nonebot-plugin-mystool#271]
LLonebot反向连接nonebot2，V11适配器
日志如下
```
03-15 15:28:27 [ERROR] nonebot | Failed to import "nonebot_plugin_mystool"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Program Files (x86)\python\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\Program Files (x86)\python\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "D:\Program Files (x86)\python\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "D:\Program Files (x86)\python\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path        
    main_content = runpy.run_path(main_path,
  File "D:\Program Files (x86)\python\lib\runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "D:\Program Files (x86)\python\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "D:\Program Files (x86)\python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\qqbot\robot\bot.py", line 46, in <module>
    nonebot.load_plugin("nonebot_plugin_mystool")   # 原神
  File "D:\Program Files (x86)\python\lib\site-packages\nonebot\plugin\load.py", line 39, in load_plugin       
    return manager.load_plugin(module_path)
> File "D:\Program Files (x86)\python\lib\site-packages\nonebot\plugin\manager.py", line 142, in load_plugin   
    module = importlib.import_module(name)
  File "D:\Program Files (x86)\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "D:\Program Files (x86)\python\lib\site-packages\nonebot\plugin\manager.py", line 242, in exec_module   
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\VAH\AppData\Roaming\Python\Python310\site-packages\nonebot_plugin_mystool\__init__.py", line 3
8, in <module>
    from .utils import CommandBegin
  File "C:\Users\VAH\AppData\Roaming\Python\Python310\site-packages\nonebot_plugin_mystool\utils\__init__.py", 
line 1, in <module>
    from .common import *
  File "C:\Users\VAH\AppData\Roaming\Python\Python310\site-packages\nonebot_plugin_mystool\utils\common.py", li
ne 34, in <module>
    from nonebot.adapters.qq import DirectMessageCreateEvent, MessageCreateEvent, \
ModuleNotFoundError: No module named 'nonebot.adapters.qq'
03-15 15:28:27 [SUCCESS] nonebot | Running NoneBot...
03-15 15:28:27 [DEBUG] nonebot | Loaded adapters: OneBot V11
03-15 15:28:27 [INFO] uvicorn | Started server process [3168]
03-15 15:28:27 [INFO] uvicorn | Waiting for application startup.
03-15 15:28:27 [INFO] nonebot_plugin_apscheduler | Scheduler Started
03-15 15:28:28 [INFO] nonebot_plugin_htmlrender | 使用 chromium 启动
03-15 15:28:28 [INFO] nonebot_plugin_htmlrender | Browser Started.
03-15 15:28:28 [INFO] nonebot_plugin_today_in_history | history_env: {}
03-15 15:28:28 [INFO] nonebot_plugin_today_in_history | history_env_all_group: False
03-15 15:28:28 [SUCCESS] nonebot_plugin_tortoise_orm | 数据库: 连接成功
03-15 15:28:28 [ERROR] uvicorn | Traceback (most recent call last):
  File "C:\Users\VAH\AppData\Roaming\Python\Python310\site-packages\starlette\routing.py", line 677, in lifespa
n
    async with self.lifespan_context(app) as maybe_state:
  File "D:\Program Files (x86)\python\lib\contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "D:\Program Files (x86)\python\lib\site-packages\nonebot\drivers\fastapi.py", line 153, in _lifespan_man
ager
    await self._lifespan.startup()
  File "D:\Program Files (x86)\python\lib\site-packages\nonebot\internal\driver\_lifespan.py", line 41, in star
tup
    await self._run_lifespan_func(self._startup_funcs)
  File "D:\Program Files (x86)\python\lib\site-packages\nonebot\internal\driver\_lifespan.py", line 37, in _run
_lifespan_func
    await run_sync(cast(SYNC_LIFESPAN_FUNC, func))()
  File "D:\Program Files (x86)\python\lib\site-packages\nonebot\utils.py", line 195, in _wrapper
    result = await loop.run_in_executor(None, partial(context.run, pfunc))
  File "D:\Program Files (x86)\python\lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\VAH\AppData\Roaming\Python\Python310\site-packages\nonebot_plugin_mystool\model\config.py", li
ne 263, in _
    plugin.metadata.config = plugin_config
AttributeError: 'NoneType' object has no attribute 'metadata'

03-15 15:28:28 [ERROR] uvicorn | Application startup failed. Exiting.
```

**Comment by Ljzd-PRO** [comment]
可能是有点问题，不过之前也没有遇到过这个情况
