### ISSUE TITLE
启动报另一个错错误，求大佬指导

### ISSUE THREAD

**Issue by VAHua** [Ljzd-PRO/nonebot-plugin-mystool#279]
```
03-19 10:06:03 [ERROR] nonebot | Failed to import "nonebot_plugin_mystool"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\Program Files (x86)\python\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "D:\Program Files (x86)\python\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "D:\Program Files (x86)\python\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "D:\Program Files (x86)\python\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path        
    main_content = runpy.run_path(main_path,
  File "D:\Program Files (x86)\python\lib\runpy.py", line 289, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "D:\Program Files (x86)\python\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "D:\Program Files (x86)\python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\qqbot\robot\bot.py", line 47, in <module>
    nonebot.load_plugin("nonebot_plugin_mystool")   # 原神
  File "D:\Program Files (x86)\python\lib\site-packages\nonebot\plugin\load.py", line 39, in load_plugin       
    return manager.load_plugin(module_path)
> File "D:\Program Files (x86)\python\lib\site-packages\nonebot\plugin\manager.py", line 142, in load_plugin   
    module = importlib.import_module(name)
  File "D:\Program Files (x86)\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "D:\Program Files (x86)\python\lib\site-packages\nonebot\plugin\manager.py", line 242, in exec_module   
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Program Files (x86)\python\lib\site-packages\nonebot_plugin_mystool\__init__.py", line 38, in <modul
e>
    from .utils import CommandBegin
  File "D:\Program Files (x86)\python\lib\site-packages\nonebot_plugin_mystool\utils\__init__.py", line 1, in <
module>
    from .common import *
  File "D:\Program Files (x86)\python\lib\site-packages\nonebot_plugin_mystool\utils\common.py", line 34, in <m
odule>
    from nonebot.adapters.qq import DirectMessageCreateEvent, MessageCreateEvent, \
ModuleNotFoundError: No module named 'nonebot.adapters.qq'
```

报错这个，但是我已经装了nonebot qq
![image](https://github.com/Ljzd-PRO/nonebot-plugin-mystool/assets/129832780/acb99510-151c-4071-9797-a049143742f4)

**Comment by dontdot** [comment]
用nb安装试试，不清楚你是不是bot装虚拟环境里了

**Comment by VAHua** [comment]
> 用nb安装试试，不清楚你是不是bot装虚拟环境里了

我靠，被你说中了，我检查了一下，然后我把插件删了，重新把包装在了用户目录下就行了，感谢大佬！
