### ISSUE TITLE
商品更新失败，ValueError: NoneBot has not been initialized.

### ISSUE THREAD

**Issue by atriatri20** [Ljzd-PRO/nonebot-plugin-mystool#282]
```
4-11 11:02:14 [SUCCESS] nonebot | OneBot V11 3481328471 | [message.private.friend]: Message -2147436566 from 1254856344 '/商品 更新'
04-11 11:02:14 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_mystool.command.exchange, lineno=291)
04-11 11:02:15 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_mystool.command.exchange, lineno=291) running complete
Process SpawnPoolWorker-4:
Process SpawnPoolWorker-8:
Process SpawnPoolWorker-6:
Process SpawnPoolWorker-10:
Traceback (most recent call last):
  File "C:\Users\18749\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\18749\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
Process SpawnPoolWorker-2:
  File "C:\Users\18749\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 114, in worker
    task = get()
Process SpawnPoolWorker-3:
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "C:\Users\18749\AppData\Local\Programs\Python\Python310\lib\multiprocessing\queues.py", line 367, in get
    return _ForkingPickler.loads(res)
  File "C:\Users\18749\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\18749\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\18749\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "F:\test\zbp_windows_amd64\nbb2\nb2\.venv\lib\site-packages\nonebot_plugin_mystool\__init__.py", line 32, in <module>
    from .model.upgrade import upgrade_plugin_data
  File "C:\Users\18749\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
Traceback (most recent call last):
  File "C:\Users\18749\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\18749\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\18749\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "F:\test\zbp_windows_amd64\nbb2\nb2\.venv\lib\site-packages\nonebot_plugin_mystool\model\__init__.py", line 2, in <module>
    from .config import *
  File "C:\Users\18749\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 114, in worker
    task = get()
  File "C:\Users\18749\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Users\18749\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 114, in worker
    task = get()
  File "C:\Users\18749\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 114, in worker
    task = get()
  File "C:\Users\18749\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "F:\test\zbp_windows_amd64\nbb2\nb2\.venv\lib\site-packages\nonebot_plugin_mystool\model\config.py", line 21, in <module>
    _driver = nonebot.get_driver()
  File "C:\Users\18749\AppData\Local\Programs\Python\Python310\lib\multiprocessing\queues.py", line 367, in get
    return _ForkingPickler.loads(res)
  File "C:\Users\18749\AppData\Local\Programs\Python\Python310\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\18749\AppData\Local\Programs\Python\Python310\lib\multiprocessing\queues.py", line 367, in get
    return _ForkingPickler.loads(res)
  File "C:\Users\18749\AppData\Local\Programs\Python\Python310\lib\multiprocessing\queues.py", line 367, in get
    return _ForkingPickler.loads(res)
  File "C:\Users\18749\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 114, in worker
    task = get()
  File "F:\test\zbp_windows_amd64\nbb2\nb2\.venv\lib\site-packages\nonebot\__init__.py", line 86, in get_driver
    raise ValueError("NoneBot has not been initialized.")
  File "F:\test\zbp_windows_amd64\nbb2\nb2\.venv\lib\site-packages\nonebot_plugin_mystool\__init__.py", line 32, in <module>
    from .model.upgrade import upgrade_plugin_data
  File "C:\Users\18749\AppData\Local\Programs\Python\Python310\lib\multiprocessing\pool.py", line 114, in worker
    task = get()
  File "F:\test\zbp_windows_amd64\nbb2\nb2\.venv\lib\site-packages\nonebot_plugin_mystool\__init__.py", line 32, in <module>
    from .model.upgrade import upgrade_plugin_data
  File "F:\test\zbp_windows_amd64\nbb2\nb2\.venv\lib\site-packages\nonebot_plugin_mystool\__init__.py", line 32, in <module>
    from .model.upgrade import upgrade_plugin_data
  File "C:\Users\18749\AppData\Local\Programs\Python\Python310\lib\multiprocessing\queues.py", line 367, in get
    return _ForkingPickler.loads(res)
ValueError: NoneBot has not been initialized.
  File "F:\test\zbp_windows_amd64\nbb2\nb2\.venv\lib\site-packages\nonebot_plugin_mystool\model\__init__.py", line 2, in <module>
    from .config import *
  File "C:\Users\18749\AppData\Local\Programs\Python\Python310\lib\multiprocessing\queues.py", line 367, in get
    return _ForkingPickler.loads(res)
  File "F:\test\zbp_windows_amd64\nbb2\nb2\.venv\lib\site-packages\nonebot_plugin_mystool\model\__init__.py", line 2, in <module>
    from .config import *
  File "F:\test\zbp_windows_amd64\nbb2\nb2\.venv\lib\site-packages\nonebot_plugin_mystool\model\__init__.py", line 2, in <module>
    from .config import *
  File "F:\test\zbp_windows_amd64\nbb2\nb2\.venv\lib\site-packages\nonebot_plugin_mystool\__init__.py", line 32, in <module>
    from .model.upgrade import upgrade_plugin_data
  File "F:\test\zbp_windows_amd64\nbb2\nb2\.venv\lib\site-packages\nonebot_plugin_mystool\model\config.py", line 21, in <module>
    _driver = nonebot.get_driver()
  File "F:\test\zbp_windows_amd64\nbb2\nb2\.venv\lib\site-packages\nonebot_plugin_mystool\__init__.py", line 32, in <module>
    from .model.upgrade import upgrade_plugin_data
  File "F:\test\zbp_windows_amd64\nbb2\nb2\.venv\lib\site-packages\nonebot_plugin_mystool\model\config.py", line 21, in <module>
    _driver = nonebot.get_driver()
  File "F:\test\zbp_windows_amd64\nbb2\nb2\.venv\lib\site-packages\nonebot_plugin_mystool\model\config.py", line 21, in <module>
    _driver = nonebot.get_driver()
  File "F:\test\zbp_windows_amd64\nbb2\nb2\.venv\lib\site-packages\nonebot_plugin_mystool\model\__init__.py", line 2, in <module>
    from .config import *
  File "F:\test\zbp_windows_amd64\nbb2\nb2\.venv\lib\site-packages\nonebot\__init__.py", line 86, in get_driver
    raise ValueError("NoneBot has not been initialized.")
  File "F:\test\zbp_windows_amd64\nbb2\nb2\.venv\lib\site-packages\nonebot_plugin_mystool\model\__init__.py", line 2, in <module>
    from .config import *
  File "F:\test\zbp_windows_amd64\nbb2\nb2\.venv\lib\site-packages\nonebot\__init__.py", line 86, in get_driver
    raise ValueError("NoneBot has not been initialized.")
ValueError: NoneBot has not been initialized.
  File "F:\test\zbp_windows_amd64\nbb2\nb2\.venv\lib\site-packages\nonebot_plugin_mystool\model\config.py", line 21, in <module>
    _driver = nonebot.get_driver()
ValueError: NoneBot has not been initialized.
  File "F:\test\zbp_windows_amd64\nbb2\nb2\.venv\lib\site-packages\nonebot_plugin_mystool\model\config.py", line 21, in <module>
    _driver = nonebot.get_driver()
  File "F:\test\zbp_windows_amd64\nbb2\nb2\.venv\lib\site-packages\nonebot\__init__.py", line 86, in get_driver
    raise ValueError("NoneBot has not been initialized.")
  File "F:\test\zbp_windows_amd64\nbb2\nb2\.venv\lib\site-packages\nonebot\__init__.py", line 86, in get_driver
    raise ValueError("NoneBot has not been initialized.")
  File "F:\test\zbp_windows_amd64\nbb2\nb2\.venv\lib\site-packages\nonebot\__init__.py", line 86, in get_driver
    raise ValueError("NoneBot has not been initialized.")
ValueError: NoneBot has not been initialized.
ValueError: NoneBot has not been initialized.
ValueError: NoneBot has not been initialized.
```

**Comment by Ljzd-PRO** [comment]
看起来Windows多进程还是有问题。用Linux或macOS的话应该不会，但目前商品列表和兑换功能也不太能用。兑换的话现在比较容易触发人机验证。

**Comment by wei-la-ya** [comment]
> 看起来Windows多进程还是有问题。用Linux或macOS的话应该不会，但目前商品列表和兑换功能也不太能用。兑换的话现在比较容易触发人机验证。

兑换功能是否能使用打码平台

**Comment by Ljzd-PRO** [comment]
目前不能

**Comment by Ljzd-PRO** [comment]
回复的有点晚😂可以设置插件配置文件中的 `good_list_image_config.MULTI_PROCESS` 为 False，关闭多进程生成商品图片。

不过商品兑换功能很久没有维护了，主要是用其他更直接的方法尝试都会触发人机验证，或者测试的时候可以正确返回，实际到时间兑换的时候又返回不明原因的错误。
