### ISSUE TITLE
兑换失败，这段报错连续发了19次

### ISSUE THREAD

**Issue by duci0007** [Ljzd-PRO/nonebot-plugin-mystool#295]
```
05-08 19:00:02 [ERROR] nonebot_plugin_mystool | 米游币商品兑换: 用户 192797865 商品 2024041712910 请求失败 - 请求发送时间: 1715166002.392409
Traceback (most recent call last):
  File "<string>", line 19, in <module>
  File "/home/l/桌面/nb2/.venv/lib/python3.10/site-packages/nonebot/__init__.py", line 334, in run
    get_driver().run(*args, **kwargs)
  File "/home/l/桌面/nb2/.venv/lib/python3.10/site-packages/nonebot/drivers/fastapi.py", line 186, in run
    uvicorn.run(
  File "/home/l/桌面/nb2/.venv/lib/python3.10/site-packages/uvicorn/main.py", line 575, in run
    server.run()
  File "/home/l/桌面/nb2/.venv/lib/python3.10/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/l/桌面/nb2/.venv/lib/python3.10/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "/home/l/桌面/nb2/.venv/lib/python3.10/site-packages/nonebot_plugin_mystool/command/exchange.py", line 458, in exchange_begin
    exchange_status, exchange_result = await good_exchange(plan)
> File "/home/l/桌面/nb2/.venv/lib/python3.10/site-packages/nonebot_plugin_mystool/api/common.py", line 1367, in good_exchange
    api_result = ApiResultHandler(res.json())
  File "/home/l/桌面/nb2/.venv/lib/python3.10/site-packages/httpx/_models.py", line 764, in json
    return jsonlib.loads(self.content, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by Ljzd-PRO** [comment]
兑换请求返回的内容不是 JSON，估计是提示 `Too Many Requests` 了，可以考虑减少插件配置中的 `exchange_thread_count` 兑换线程数，每个兑换线程都会持续指定的时间循环发送兑换请求，可能 1 个就足够了。

目前 dev 分支已经加上了返回的原始内容的日志输出
