### ISSUE TITLE
设置多个分区的米游币任务，只执行《综合》分区

### ISSUE THREAD

**Issue by duki-web** [Ljzd-PRO/nonebot-plugin-mystool#312]
为什么我设置了多个分区的米游币任务=（100米游币），它执行完《综合》分区=（90米游币），执行其他分区失败后就再也不执行其他分区任务了，多账户也是一样的。
环境：高通410（开发板）
架构：arm64
系统：Debian11
IP：国内IP

**Comment by duki-web** [comment]
```
06-14 16:43:08 [DEBUG] nonebot | QQ | Bot 1xxxxxx0  calling API guilds
06-14 16:43:08 [DEBUG] nonebot | Checking for matchers completed
06-14 16:43:12 [SUCCESS] nonebot | QQ 1xxxxxx0  | [DIRECT_MESSAGE_CREATE]: Message 0886b1e28293c8d8a0e50110a9c9a38abaeacd7838f909489f85b0b306 from 　x®: [Text(type='text', data={'text': '/任务'})]
06-14 16:43:12 [DEBUG] nonebot | Checking for matchers in priority 1...
06-14 16:43:12 [DEBUG] nonebot | Checking for matchers in priority 4...
06-14 16:43:12 [DEBUG] nonebot | Checking for matchers in priority 5...
06-14 16:43:12 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_mystool.command.plan, lineno=86)
06-14 16:43:12 [DEBUG] nonebot | Running Matcher(type='message', module=nonebot_plugin_mystool.command.plan, lineno=86)
06-14 16:43:12 [DEBUG] nonebot | Running handler Dependent(call=_)
06-14 16:43:12 [DEBUG] nonebot | QQ | Bot 1xxxxxx0  calling API post_dms_messages
06-14 16:43:14 [DEBUG] nonebot | QQ | Bot 1xxxxxx0  calling API get_channels
06-14 16:43:29 [DEBUG] nonebot | QQ | Bot 1xxxxxx0  calling API post_dms_messages
06-14 16:44:45 [DEBUG] nonebot_plugin_mystool | 检查点赞返回：content={'retcode': 0, 'message': 'OK', 'data': {}} data={} message='OK' retcode=0
06-14 16:44:52 [DEBUG] nonebot_plugin_mystool | 检查点赞返回：content={'retcode': 0, 'message': 'OK', 'data': {}} data={} message='OK' retcode=0
06-14 16:45:00 [DEBUG] nonebot_plugin_mystool | 检查点赞返回：content={'retcode': 0, 'message': 'OK', 'data': {}} data={} message='OK' retcode=0
06-14 16:45:08 [DEBUG] nonebot_plugin_mystool | 检查点赞返回：content={'retcode': 0, 'message': 'OK', 'data': {}} data={} message='OK' retcode=0
06-14 16:45:21 [DEBUG] nonebot_plugin_mystool | 检查点赞返回：content={'retcode': 0, 'message': 'OK', 'data': {}} data={} message='OK' retcode=0
06-14 16:45:29 [DEBUG] nonebot_plugin_mystool | 检查点赞返回：content={'retcode': 0, 'message': 'OK', 'data': {}} data={} message='OK' retcode=0
06-14 16:45:37 [DEBUG] nonebot_plugin_mystool | 检查点赞返回：content={'retcode': 0, 'message': 'OK', 'data': {}} data={} message='OK' retcode=0
06-14 16:45:44 [DEBUG] nonebot_plugin_mystool | 检查点赞返回：content={'retcode': 0, 'message': 'OK', 'data': {}} data={} message='OK' retcode=0
06-14 16:45:57 [DEBUG] nonebot_plugin_mystool | 检查点赞返回：content={'retcode': 0, 'message': 'OK', 'data': {}} data={} message='OK' retcode=0
06-14 16:46:05 [DEBUG] nonebot_plugin_mystool | 检查点赞返回：content={'retcode': 0, 'message': 'OK', 'data': {}} data={} message='OK' retcode=0
06-14 16:46:22 [DEBUG] nonebot | QQ | Bot 1xxxxxx0  calling API post_dms_messages
06-14 16:46:28 [DEBUG] nonebot | QQ | Bot 1xxxxxx0  calling API post_dms_messages
06-14 16:47:47 [DEBUG] nonebot_plugin_mystool | 检查点赞返回：content={'retcode': 0, 'message': 'OK', 'data': {}} data={} message='OK' retcode=0
06-14 16:47:55 [DEBUG] nonebot_plugin_mystool | 检查点赞返回：content={'retcode': 0, 'message': 'OK', 'data': {}} data={} message='OK' retcode=0
06-14 16:48:02 [DEBUG] nonebot_plugin_mystool | 检查点赞返回：content={'retcode': 0, 'message': 'OK', 'data': {}} data={} message='OK' retcode=0
06-14 16:48:10 [DEBUG] nonebot_plugin_mystool | 检查点赞返回：content={'retcode': 0, 'message': 'OK', 'data': {}} data={} message='OK' retcode=0
06-14 16:48:23 [DEBUG] nonebot_plugin_mystool | 检查点赞返回：content={'retcode': 0, 'message': 'OK', 'data': {}} data={} message='OK' retcode=0
06-14 16:48:31 [DEBUG] nonebot_plugin_mystool | 检查点赞返回：content={'retcode': 0, 'message': 'OK', 'data': {}} data={} message='OK' retcode=0
06-14 16:48:39 [DEBUG] nonebot_plugin_mystool | 检查点赞返回：content={'retcode': 0, 'message': 'OK', 'data': {}} data={} message='OK' retcode=0
06-14 16:48:46 [DEBUG] nonebot_plugin_mystool | 检查点赞返回：content={'retcode': 0, 'message': 'OK', 'data': {}} data={} message='OK' retcode=0
06-14 16:49:00 [DEBUG] nonebot_plugin_mystool | 检查点赞返回：content={'retcode': 0, 'message': 'OK', 'data': {}} data={} message='OK' retcode=0
06-14 16:49:08 [DEBUG] nonebot_plugin_mystool | 检查点赞返回：content={'retcode': 0, 'message': 'OK', 'data': {}} data={} message='OK' retcode=0
06-14 16:49:25 [DEBUG] nonebot | QQ | Bot 1xxxxxx0  calling API post_dms_messages
06-14 16:49:30 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_mystool.command.plan, lineno=86) running complete
06-14 16:49:30 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_mystool.command.plan, lineno=86) failed.
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "/root/mikl/.venv/lib/python3.9/site-packages/nonebot/__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "/root/mikl/.venv/lib/python3.9/site-packages/nonebot/drivers/none.py", line 56, in run
    loop.run_until_complete(self._serve())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1890, in _run_once
    handle._run()
  File "/usr/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/root/mikl/.venv/lib/python3.9/site-packages/nonebot/message.py", line 476, in check_and_run_matcher
    await _run_matcher(
> File "/root/mikl/.venv/lib/python3.9/site-packages/nonebot/message.py", line 428, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/root/mikl/.venv/lib/python3.9/site-packages/nonebot/internal/matcher/matcher.py", line 850, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/root/mikl/.venv/lib/python3.9/site-packages/nonebot/internal/matcher/matcher.py", line 825, in simple_run
    await handler(
  File "/root/mikl/.venv/lib/python3.9/site-packages/nonebot/dependencies/__init__.py", line 94, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/root/mikl/.venv/lib/python3.9/site-packages/nonebot_plugin_mystool/command/plan.py", line 132, in _
    await perform_bbs_sign(user=user, user_ids=[user_id], matcher=matcher)
  File "/root/mikl/.venv/lib/python3.9/site-packages/nonebot_plugin_mystool/command/plan.py", line 422, in perform_bbs_sign
    await matcher.send(
  File "/root/mikl/.venv/lib/python3.9/site-packages/nonebot/internal/matcher/matcher.py", line 566, in send
    return await bot.send(event=event, message=_message, **kwargs)
  File "/root/mikl/.venv/lib/python3.9/site-packages/nonebot/adapters/qq/bot.py", line 483, in send
    return await self.send_to_dms(
  File "/root/mikl/.venv/lib/python3.9/site-packages/nonebot/adapters/qq/bot.py", line 349, in send_to_dms
    return await self.post_dms_messages(
  File "/root/mikl/.venv/lib/python3.9/site-packages/nonebot/internal/adapter/bot.py", line 122, in call_api
    raise exception
  File "/root/mikl/.venv/lib/python3.9/site-packages/nonebot/internal/adapter/bot.py", line 97, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "/root/mikl/.venv/lib/python3.9/site-packages/nonebot/adapters/qq/adapter.py", line 419, in _call_api
    return await api_handler(bot, **data)
  File "/root/mikl/.venv/lib/python3.9/site-packages/nonebot/adapters/qq/utils.py", line 64, in __call__
    return await self.func(inst, *args, **kwds)
  File "/root/mikl/.venv/lib/python3.9/site-packages/nonebot/adapters/qq/bot.py", line 1081, in post_dms_messages
    return type_validate_python(GuildMessage, await self._request(request))
  File "/root/mikl/.venv/lib/python3.9/site-packages/nonebot/adapters/qq/bot.py", line 551, in _request
    return self._handle_response(response)
  File "/root/mikl/.venv/lib/python3.9/site-packages/nonebot/adapters/qq/bot.py", line 540, in _handle_response
    raise ActionFailed(response)
nonebot.adapters.qq.exception.ActionFailed: <ActionFailed: 500, code=304027, message=message is expired, trace_id=8102db46e1bb38e321affc8a3a3f72cd>
06-14 16:49:30 [DEBUG] nonebot | Stop event propagation
06-14 16:49:30 [DEBUG] nonebot | Checking for matchers completed
06-14 16:52:11 [SUCCESS] nonebot | QQ 1xxxxxx0  | [DIRECT_MESSAGE_CREATE]: Message 0886b1e28293c8d8a0e50110a9c9a38abaeacd7838fe0948ba89b0b306 from 　x®: [Text(type='text', data={'text': '/任务'})]
06-14 16:52:11 [DEBUG] nonebot | Checking for matchers in priority 1...
06-14 16:52:11 [DEBUG] nonebot | Checking for matchers in priority 4...
06-14 16:52:11 [DEBUG] nonebot | Checking for matchers in priority 5...
06-14 16:52:11 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_mystool.command.plan, lineno=86)
06-14 16:52:11 [DEBUG] nonebot | Running Matcher(type='message', module=nonebot_plugin_mystool.command.plan, lineno=86)
06-14 16:52:11 [DEBUG] nonebot | Running handler Dependent(call=_)
06-14 16:52:11 [DEBUG] nonebot | QQ | Bot 1xxxxxx0 calling API post_dms_messages
06-14 16:52:39 [DEBUG] nonebot | QQ | Bot 1xxxxxx0  calling API post_dms_messages
06-14 16:52:45 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_mystool.command.plan, lineno=86) running complete
06-14 16:52:45 [DEBUG] nonebot | Stop event propagation
06-14 16:52:45 [DEBUG] nonebot | Checking for matchers completed
```

**这是报错日志**

**Comment by Ljzd-PRO** [comment]
报错的话是适配器相关的问题

**Comment by Ljzd-PRO** [comment]
那应该是因为发送消息的时候有异常被抛出，导致任务中断了，可能是图片没有发出去？

**Comment by duki-web** [comment]
> 那应该是因为发送消息的时候有异常被抛出，导致任务中断了，可能是图片没有发出去？

**06-14 16:52:11** 这里我又执行 /任务 还是没执行其他分区任务，反馈回来的信息是 米游币任务执行完成

**Comment by Ljzd-PRO** [comment]
> > 那应该是因为发送消息的时候有异常被抛出，导致任务中断了，可能是图片没有发出去？
> 
> **06-14 16:52:11** 这里我又执行 /任务 还是没执行其他分区任务，反馈回来的信息是 米游币任务执行完成

如果查询到可完成的米游币任务都完成了的话，就会跳过。所以主要是获取米游币，多分区的话是比较偏辅助作用的

**Comment by duki-web** [comment]
了解
