### ISSUE TITLE
安装之后启动不了，但是删了之后就能启动

### ISSUE THREAD

**Issue by duci0007** [Ljzd-PRO/nonebot-plugin-mystool#313]
06-15 18:32:33 [WARNING] nonebot | Unknown ForwardRef["Matcher"] for parameter matcher
Traceback (most recent call last):
  File "<string>", line 18, in <module>
  File "/root/nb2/.venv/lib/python3.12/site-packages/nonebot/plugin/load.py", line 131, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/root/nb2/.venv/lib/python3.12/site-packages/nonebot/plugin/load.py", line 65, in load_all_plugins
    return manager.load_all_plugins()
  File "/root/nb2/.venv/lib/python3.12/site-packages/nonebot/plugin/manager.py", line 203, in load_all_plugins
    return set(
  File "/root/nb2/.venv/lib/python3.12/site-packages/nonebot/plugin/manager.py", line 204, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
  File "/root/nb2/.venv/lib/python3.12/site-packages/nonebot/plugin/manager.py", line 167, in load_plugin
    module = importlib.import_module(self._third_party_plugin_ids[name])
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "/root/nb2/.venv/lib/python3.12/site-packages/nonebot/plugin/manager.py", line 255, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/root/nb2/.venv/lib/python3.12/site-packages/nonebot_plugin_mystool/__init__.py", line 57, in <module>
    from .command import *
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/root/nb2/.venv/lib/python3.12/site-packages/nonebot_plugin_mystool/command/__init__.py", line 7, in <module>
    from .setting import *
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/root/nb2/.venv/lib/python3.12/site-packages/nonebot_plugin_mystool/command/setting.py", line 321, in <module>
    @global_setting.got('choice')
  File "/root/nb2/.venv/lib/python3.12/site-packages/nonebot/internal/matcher/matcher.py", line 540, in _decorator
    cls.append_handler(func, parameterless=_parameterless)
  File "/root/nb2/.venv/lib/python3.12/site-packages/nonebot/internal/matcher/matcher.py", line 433, in append_handler
    handler_ = Dependent[Any].parse(
  File "/root/nb2/.venv/lib/python3.12/site-packages/nonebot/dependencies/__init__.py", line 161, in parse
    else cls.parse_parameterless(tuple(parameterless), allow_types)
  File "/root/nb2/.venv/lib/python3.12/site-packages/nonebot/dependencies/__init__.py", line 140, in parse_parameterless
    if param := allow_type._check_parameterless(value, allow_types):
  File "/root/nb2/.venv/lib/python3.12/site-packages/nonebot/internal/params.py", line 178, in _check_parameterless
    dependent = Dependent[Any].parse(
  File "/root/nb2/.venv/lib/python3.12/site-packages/nonebot/dependencies/__init__.py", line 157, in parse
    params = cls.parse_params(call, allow_types)
  File "/root/nb2/.venv/lib/python3.12/site-packages/nonebot/dependencies/__init__.py", line 106, in parse_params
    params = get_typed_signature(call).parameters.values()
  File "/root/nb2/.venv/lib/python3.12/site-packages/nonebot/dependencies/utils.py", line 27, in get_typed_signature
    annotation=get_typed_annotation(param, globalns),
> File "/root/nb2/.venv/lib/python3.12/site-packages/nonebot/dependencies/utils.py", line 41, in get_typed_annotation
    annotation = evaluate_forwardref(annotation, globalns, globalns)
  File "/root/nb2/.venv/lib/python3.12/site-packages/nonebot/typing.py", line 107, in evaluate_forwardref
    return ref._evaluate(globalns, localns, frozenset())
TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard'
06-15 18:32:33 [SUCCESS] nonebot | Succeeded to load plugin "nonebot_plugin_mystool"
06-15 18:32:33 [SUCCESS] nonebot | Running NoneBot...
06-15 18:32:33 [INFO] uvicorn | Started server process [347787]
06-15 18:32:33 [INFO] uvicorn | Waiting for application startup.
06-15 18:32:33 [INFO] nonebot_plugin_apscheduler | Scheduler Started
06-15 18:32:33 [INFO] uvicorn | Application startup complete.
06-15 18:32:33 [ERROR] uvicorn | [Errno 99] error while attempting to bind on address ('106.14.72.113', 9999): cannot assign requested address
06-15 18:32:33 [INFO] uvicorn | Waiting for application shutdown.
06-15 18:32:33 [INFO] nonebot_plugin_apscheduler | Scheduler Shutdown
06-15 18:32:33 [INFO] uvicorn | Application shutdown complete.
[root@iZuf6j5qwqdhmltsibw0g2Z nb2]#

**Comment by mengluo04** [comment]
你阿里云的9999端口开了没

**Comment by duci0007** [comment]
我开放全端口了

**Comment by duci0007** [comment]
我把端口改成其他的也不行

**Comment by mengluo04** [comment]
> 我把端口改成其他的也不行

截图看看你的安全组，还有你为啥要去连接这个地址，是啥服务，这是在nb2里面的
