### ISSUE TITLE
原神签到失败

### ISSUE THREAD

**Issue by ytgo** [Ljzd-PRO/nonebot-plugin-mystool#32]
⚠️账户 xxxxx 🎮『原神』签到失败！请尝试重新签到，若多次失败请尝试重新登录绑定账户

所有的号签到都失败了

**Comment by Ljzd-PRO** [comment]
看一下日志

**Comment by ytgo** [comment]
是不是字体原因
10-09 19:40:23 [INFO] nonebot_plugin_mystool | 正在校对互联网时间
10-09 19:40:23 [INFO] nonebot_plugin_mystool | 系统时间与网络时间的误差为 -0.05 秒
10-09 19:40:23 [WARNING] nonebot_plugin_mystool | 商品列表图片生成 - 缺少字体，正在从 https://github.com/adobe-fonts/source-han-sans/tree/release 下载字体...
10-09 19:40:40 [ERROR] nonebot_plugin_mystool | 下载文件 - https://ghproxy.com/https://github.com/adobe-fonts/source-han-sans/releases/download/2.004R/SourceHanSansHWSC.zip 失败
10-09 19:40:40 [DEBUG] nonebot_plugin_mystool | ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/httpcore/_exceptions.py", line 8, in map_exceptions
    yield
  File "/usr/local/lib/python3.9/dist-packages/httpcore/backends/asyncio.py", line 76, in start_tls
    raise exc
  File "/usr/local/lib/python3.9/dist-packages/httpcore/backends/asyncio.py", line 67, in start_tls
    ssl_stream = await anyio.streams.tls.TLSStream.wrap(
  File "/usr/local/lib/python3.9/dist-packages/anyio/streams/tls.py", line 122, in wrap
    await wrapper._call_sslobject_method(ssl_object.do_handshake)
  File "/usr/local/lib/python3.9/dist-packages/anyio/streams/tls.py", line 137, in _call_sslobject_method
    data = await self.transport_stream.receive()
  File "/usr/local/lib/python3.9/dist-packages/anyio/_backends/_asyncio.py", line 1274, in receive
    raise self._protocol.exception
anyio.BrokenResourceError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.9/dist-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/usr/local/lib/python3.9/dist-packages/httpcore/_async/connection_pool.py", line 253, in handle_async_request
    raise exc
  File "/usr/local/lib/python3.9/dist-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "/usr/local/lib/python3.9/dist-packages/httpcore/_async/connection.py", line 86, in handle_async_request
    raise exc
  File "/usr/local/lib/python3.9/dist-packages/httpcore/_async/connection.py", line 63, in handle_async_request
    stream = await self._connect(request)
  File "/usr/local/lib/python3.9/dist-packages/httpcore/_async/connection.py", line 150, in _connect
    stream = await stream.start_tls(**kwargs)
  File "/usr/local/lib/python3.9/dist-packages/httpcore/backends/asyncio.py", line 76, in start_tls
    raise exc
  File "/usr/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.9/dist-packages/httpcore/_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/nonebot_plugin_mystool/utils.py", line 180, in get_file
    res = await client.get(url, timeout=conf.TIME_OUT, follow_redirects=True)
  File "/usr/local/lib/python3.9/dist-packages/httpx/_client.py", line 1751, in get
    return await self.request(
  File "/usr/local/lib/python3.9/dist-packages/httpx/_client.py", line 1527, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/local/lib/python3.9/dist-packages/httpx/_client.py", line 1614, in send
    response = await self._send_handling_auth(
  File "/usr/local/lib/python3.9/dist-packages/httpx/_client.py", line 1642, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/usr/local/lib/python3.9/dist-packages/httpx/_client.py", line 1679, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/usr/local/lib/python3.9/dist-packages/httpx/_client.py", line 1716, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/usr/local/lib/python3.9/dist-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/usr/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.9/dist-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/nonebot_plugin_mystool/utils.py", line 177, in get_file
    async for attempt in tenacity.AsyncRetrying(stop=custom_attempt_times(retry), wait=tenacity.wait_fixed(conf.SLEEP_TIME_RETRY)):
  File "/usr/local/lib/python3.9/dist-packages/tenacity/_asyncio.py", line 69, in __anext__
    do = self.iter(retry_state=self._retry_state)
  File "/usr/local/lib/python3.9/dist-packages/tenacity/__init__.py", line 363, in iter
    raise retry_exc from fut.exception()
tenacity.RetryError: RetryError[<Future at 0x7f14152aba30 state=finished raised ConnectError>]

10-09 19:40:40 [ERROR] nonebot_plugin_mystool | 商品列表图片生成 - 字体下载失败，无法继续生成图片

**Comment by Everything0519** [comment]
可以看一下原神签到失败部分的日志 感觉有可能是网络的问题 重启试试看字体还能不能成功下载吧 字体下载成功后就不会再下载了

**Comment by Ljzd-PRO** [comment]
如果有代理软件可能需要关闭

**Comment by shelter132** [comment]
同样遇到了签到失败的问题，但是启动时无报错，发送签到命令后日志中提示
![YMS@({CZ3JXRIMYY2@S{EC](https://user-images.githubusercontent.com/99066443/215750363-c343dde9-122f-4e7f-876b-3dc7d7b2d87f.png)

**Comment by Ljzd-PRO** [comment]
目前原神签到确实有问题，但是崩坏三签到没问题。
如果刚进行登陆绑定不久的账号可以成功，可以试试给那些签到失败的账号重新登陆。

**Comment by Akaisorani** [comment]
@Ljzd-PRO @shelter132 
**解决方案：**
config文件中
salt (ios)值 替换成 ulInCDohgEs557j0VsPDYnQaaz6KJcv5
x-rpc-app_version值 改为 2.28.1
方案来源：[https://ngabbs.com/read.php?tid=32936520](https://ngabbs.com/read.php?tid=32936520)

**Comment by Ljzd-PRO** [comment]
现在可以直接尝试签到操作，在线获取的config.json已经更新，但只有salt可以变更，目前的版本x-rpc-app_version没法变更。
