### ISSUE TITLE
插件载入失败，无论是nb-lib还是pip

### ISSUE THREAD

**Issue by ShaoNian-end** [Ljzd-PRO/nonebot-plugin-mystool#33]
nb run 启动后提示
ImportError: cannot import name 'export' from 'nonebot' (/root/L/N/venv/lib/python3.9/site-packages/nonebot/__init__.py)
通过了解到新版本nb2移除了export，希望作者能够适配一下

**Comment by Ljzd-PRO** [comment]
有完整的报错吗？例如在第几行。因为看这样的话比较像是nonebot自身就启动失败了。

**Comment by dd178** [comment]
一样的问题，完整报错：
```
11-06 20:39:15 [SUCCESS] nonebot | NoneBot is initializing...
11-06 20:39:15 [INFO] nonebot | Current Env: dev
11-06 20:39:15 [DEBUG] nonebot | Loaded Config: {'driver': '~fastapi', 'host': IPv4Address('127.0.0.1'), 'port': 8080, 'log_level': 'DEBUG', 'api_timeout': 30.0, 'superusers': set(), 'nickname': set(), 'command_start': {'/'}, 'command_sep': {'.'}, 'session_expire_timeout': datetime.timedelta(seconds=120), 'environment': 'dev', 'fastapi_reload': True}
11-06 20:39:15 [DEBUG] nonebot | Succeeded to load adapter "OneBot V11"
11-06 20:39:15 [SUCCESS] nonebot | Succeeded to import "single_session"
11-06 20:39:15 [ERROR] nonebot | Failed to import "nonebot_plugin_mystool"
Traceback (most recent call last):
  File "/usr/local/python3.9/bin/nb", line 8, in <module>
    sys.exit(main())
  File "/usr/local/python3.9/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/python3.9/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/python3.9/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/python3.9/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/python3.9/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/python3.9/lib/python3.9/site-packages/nb_cli/commands/main.py", line 30, in run
    run_bot(file, app)
  File "/usr/local/python3.9/lib/python3.9/site-packages/nb_cli/handlers/deploy.py", line 20, in run_bot
    module = importlib.import_module(module_name)
  File "/usr/local/python3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/root/mystool/./bot.py", line 27, in <module>
    nonebot.load_from_toml("pyproject.toml")
  File "/usr/local/python3.9/lib/python3.9/site-packages/nonebot/plugin/load.py", line 122, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "/usr/local/python3.9/lib/python3.9/site-packages/nonebot/plugin/load.py", line 59, in load_all_plugins
    return manager.load_all_plugins()
  File "/usr/local/python3.9/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 168, in load_all_plugins
    return set(
  File "/usr/local/python3.9/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 169, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "/usr/local/python3.9/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "/usr/local/python3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/usr/local/python3.9/lib/python3.9/site-packages/nonebot/plugin/manager.py", line 233, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/python3.9/lib/python3.9/site-packages/nonebot_plugin_mystool/__init__.py", line 70, in <module>
    __import__(file, globals(), level=1)
  File "/usr/local/python3.9/lib/python3.9/site-packages/nonebot_plugin_mystool/addFriend.py", line 9, in <module>
    from nonebot_plugin_apscheduler import scheduler
  File "/usr/local/python3.9/lib/python3.9/site-packages/nonebot_plugin_apscheduler/__init__.py", line 3, in <module>
    from nonebot import export, get_driver
ImportError: cannot import name 'export' from 'nonebot' (/usr/local/python3.9/lib/python3.9/site-packages/nonebot/__init__.py)
11-06 20:39:15 [SUCCESS] nonebot | Running NoneBot...
11-06 20:39:15 [DEBUG] nonebot | Loaded adapters: OneBot V11
11-06 20:39:15 [INFO] uvicorn | Will watch for changes in these directories: ['/root/mystool']
11-06 20:39:15 [ERROR] uvicorn | [Errno 98] Address already in use

```

**Comment by Ljzd-PRO** [comment]
这里看上去是 `nonebot_plugin_apscheduler` 导致的。这是nonebot团队开发的的插件，如果nonebot2新版本作了修改，那可以尝试更新一下`nonebot_plugin_apscheduler`。
> ```
>  File "/usr/local/python3.9/lib/python3.9/site-packages/nonebot_plugin_mystool/addFriend.py", line 9, in <module>
>     from nonebot_plugin_apscheduler import scheduler
>   File "/usr/local/python3.9/lib/python3.9/site-packages/nonebot_plugin_apscheduler/__init__.py", line 3, in <module>
>     from nonebot import export, get_driver
>  ImportError: cannot import name 'export' from 'nonebot' (/usr/local/python3.9/lib/python3.9/site-packages/nonebot/__init__.py)
>  ```

**Comment by 136585816** [comment]
把 `nonebot_plugin_apscheduler` 更新到0.2.0解决了
