### ISSUE TITLE
打卡人机验证无法通过

### ISSUE THREAD

**Issue by haoeixc** [Ljzd-PRO/nonebot-plugin-mystool#347]
版本v2.7.0且已经接入打码平台，签到任务均可完成人机验证
![111](https://github.com/user-attachments/assets/88fcb9fe-1ee3-4771-ab68-afdc1e7c9c08)
但米游币任务除了打卡不能通过人机验证，其他都可以
![QQ](https://github.com/user-attachments/assets/dd1ddd08-b913-47e8-82be-341d3a62ffc6)

**Comment by Tom-and-Jerry-childhood** [comment]
能教一下游戏签到怎么通过人机验证吗

**Comment by Ljzd-PRO** [comment]
米游币签到的时候看一下日志有没有报错

**Comment by haoeixc** [comment]
> 米游币签到的时候看一下日志有没有报错

我的号任务现在基本都能完成（不知道是不是手动签后人机验证没了），但是后台还有报错的（任务已经完成），其他用户也有报错
![131f09f0-9b5e-48a9-9422-8c3ab073dc7b](https://github.com/user-attachments/assets/ce2d068f-aa38-4769-9327-777e95eb9732)
如上图，粉线上面是我的号，下面是其他账号，他的签到情况有点糟糕
![QQ_1721755253150](https://github.com/user-attachments/assets/69fdace7-3a10-45dc-84c1-5861587e7682)

**Comment by haoeixc** [comment]
> 能教一下游戏签到怎么通过人机验证吗

要接打码平台的，你可以去看下这个issue
#281 懒得弄接直接部署他这个就可以了https://github.com/Sakamakiiizayoi/ttocr_auto

**Comment by haoeixc** [comment]
很奇怪的情况，打码平台上我锁定appkey后，执行签到和米游币任务（此issue开头图片），接入打码平台的后端提示说appkey已锁定请解锁后使用，但是还是返回了gt和challenge（这是签到任务并且完成了）但是到了米游币任务，机器人就开始报错如上面的图，最奇怪的是此时签到不消耗打码平台的打码积分!!!，签到都能过，任务每次都有一两个过不了；我在打码平台上解锁appkey后所有签到和任务都正常了（打码积分也开始扣了）

**Comment by haoeixc** [comment]
我再观察几波

**Comment by dontdot** [comment]
```
07-25 07:01:42 [WARNING] nonebot_plugin_mystool | 游戏签到 - 用户 17xxxxxxxx5 可能被人机验证阻拦
07-25 07:01:42 [DEBUG] nonebot_plugin_mystool | 网络请求返回: {"retcode":0,"message":"OK","data":{"code":"","risk_code":5001,"gt":"afxxxxxxxxxxxxxxxxxxxxxf86ce8","challenge":"105xxxxxxxxxxxxxxxxxxxxxx6627e5f","success":1,"is_risk":true}}
```
这是正常弹出验证码的debug日志，针对 `'NoneType' object has no attribute 'get'` 打印出`res.text`看看

**Comment by haoeixc** [comment]
> ```
> 07-25 07:01:42 [WARNING] nonebot_plugin_mystool | 游戏签到 - 用户 17xxxxxxxx5 可能被人机验证阻拦
> 07-25 07:01:42 [DEBUG] nonebot_plugin_mystool | 网络请求返回: {"retcode":0,"message":"OK","data":{"code":"","risk_code":5001,"gt":"afxxxxxxxxxxxxxxxxxxxxxf86ce8","challenge":"105xxxxxxxxxxxxxxxxxxxxxx6627e5f","success":1,"is_risk":true}}
> ```
> 
> 这是正常弹出验证码的debug日志，针对 `'NoneType' object has no attribute 'get'` 打印出`res.text`看看

![捕获44433](https://github.com/user-attachments/assets/d57c913a-bd41-4e5b-b7a3-1aa210f3000b)
破案了，是打码平台的问题，锁定appkey签到能过（和你发的示例一样）但任务过不了（奇怪），平台开锁appkey现在都稳过了

**Comment by Tom-and-Jerry-childhood** [comment]
> > 能教一下游戏签到怎么通过人机验证吗
> 
> 要接打码平台的，你可以去看下这个issue #281 懒得弄接直接部署他这个就可以了https://github.com/Sakamakiiizayoi/ttocr_auto

OK我抽空研究一下，谢谢。

**Comment by 512434** [comment]
我出现了个错误，签到无法成功，大佬们帮我看下
11-21 00:03:00 [ERROR] nonebot_plugin_mystool | 获取人机验证validate失败
Traceback (most recent call last):
  File "/home/software/ocgbot/ocgBot/.venv/lib/python3.9/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/home/software/ocgbot/ocgBot/.venv/lib/python3.9/site-packages/httpx/_transports/default.py", line 373, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/home/software/ocgbot/ocgBot/.venv/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "/home/software/ocgbot/ocgBot/.venv/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
  File "/home/software/ocgbot/ocgBot/.venv/lib/python3.9/site-packages/httpcore/_async/connection.py", line 99, in handle_async_request
    raise exc
  File "/home/software/ocgbot/ocgBot/.venv/lib/python3.9/site-packages/httpcore/_async/connection.py", line 76, in handle_async_request
    stream = await self._connect(request)
  File "/home/software/ocgbot/ocgBot/.venv/lib/python3.9/site-packages/httpcore/_async/connection.py", line 122, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
  File "/home/software/ocgbot/ocgBot/.venv/lib/python3.9/site-packages/httpcore/_backends/auto.py", line 30, in connect_tcp
    return await self._backend.connect_tcp(
  File "/home/software/ocgbot/ocgBot/.venv/lib/python3.9/site-packages/httpcore/_backends/anyio.py", line 123, in connect_tcp
    stream._raw_socket.setsockopt(*option)  # type: ignore[attr-defined] # pragma: no cover
  File "/usr/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/software/ocgbot/ocgBot/.venv/lib/python3.9/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "/home/software/ocgbot/ocgBot/.venv/lib/python3.9/site-packages/nonebot/__init__.py", line 335, in run
    get_driver().run(*args, **kwargs)
  File "/home/software/ocgbot/ocgBot/.venv/lib/python3.9/site-packages/nonebot/drivers/fastapi.py", line 186, in run
    uvicorn.run(
  File "/home/software/ocgbot/ocgBot/.venv/lib/python3.9/site-packages/uvicorn/main.py", line 577, in run
    server.run()
  File "/home/software/ocgbot/ocgBot/.venv/lib/python3.9/site-packages/uvicorn/server.py", line 65, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/software/ocgbot/ocgBot/.venv/lib/python3.9/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "/home/software/ocgbot/ocgBot/.venv/lib/python3.9/site-packages/nonebot_plugin_mystool/command/plan.py", line 812, in daily_schedule
    await perform_game_sign(user=user, user_ids=user_ids)
  File "/home/software/ocgbot/ocgBot/.venv/lib/python3.9/site-packages/nonebot_plugin_mystool/command/plan.py", line 281, in perform_game_sign
    if not (geetest_result := await get_validate(user, mmt_data.gt, mmt_data.challenge)):
> File "/home/software/ocgbot/ocgBot/.venv/lib/python3.9/site-packages/nonebot_plugin_mystool/utils/common.py", line 265, in get_validate
    res = await client.post(
  File "/home/software/ocgbot/ocgBot/.venv/lib/python3.9/site-packages/httpx/_client.py", line 1892, in post
    return await self.request(
  File "/home/software/ocgbot/ocgBot/.venv/lib/python3.9/site-packages/httpx/_client.py", line 1574, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/home/software/ocgbot/ocgBot/.venv/lib/python3.9/site-packages/httpx/_client.py", line 1661, in send
    response = await self._send_handling_auth(
  File "/home/software/ocgbot/ocgBot/.venv/lib/python3.9/site-packages/httpx/_client.py", line 1689, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/home/software/ocgbot/ocgBot/.venv/lib/python3.9/site-packages/httpx/_client.py", line 1726, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/home/software/ocgbot/ocgBot/.venv/lib/python3.9/site-packages/httpx/_client.py", line 1763, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/home/software/ocgbot/ocgBot/.venv/lib/python3.9/site-packages/httpx/_transports/default.py", line 373, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/usr/lib/python3.9/contextlib.py", line 135, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/software/ocgbot/ocgBot/.venv/lib/python3.9/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: All connection attempts failed
