### ISSUE TITLE
发送米游社商店图片时报错

### ISSUE THREAD

**Issue by YuYue-Amatsuki** [Ljzd-PRO/nonebot-plugin-mystool#36]
后台报错如下
```
11-26 20:57:17 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_mystool.exchangePlan) running complete
11-26 20:57:17 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_mystool.exchangePlan) failed.
Traceback (most recent call last):
  File "C:\Users\YuYue\Desktop\yuyue_bot\bot.py", line 38, in <module>
    nonebot.run(app="__mp_main__:app")
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run
    uvicorn.run(
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 188, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher\matcher.py", line 727, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher\matcher.py", line 702, in simple_run
    await handler(
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_mystool\exchangePlan.py", line 329, in _
    await get_good_image.finish(MessageSegment.image('file:///'+img_path))
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher\matcher.py", line 476, in finish
    await cls.send(message, **kwargs)
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher\matcher.py", line 461, in send
    return await bot.send(event=event, message=_message, **kwargs)
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\adapters\onebot\v11\bot.py", line 220, in send
    return await self.__class__.send_handler(self, event, message, **kwargs)
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\adapters\onebot\v11\bot.py", line 175, in send
    return await bot.send_msg(**params)
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\adapter\bot.py", line 120, in call_api
    raise exception
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\adapter\bot.py", line 98, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\adapters\onebot\v11\adapter.py", line 132, in _call_api
    return handle_api_result(
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\adapters\onebot\v11\utils.py", line 58, in handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.onebot.v11.exception.ActionFailed: <ActionFailed data=None, echo='44', msg='SEND_MSG_API_ERROR', retcode=100, status='failed', wording='请参考 go-cqhttp 端输出'>
```
go-cqhttp报错如下
```
[2022-11-26 20:57:17] [WARNING]: 转换CQ码 ({"type": "image", "data": {"file": "file:///C:\\Users\\YuYue\\Desktop\\yuyue_bot\\data\\nonebot-plugin-mystool/11-26-ys.jpg", "type": null, "cache": "true", "proxy": "true", "timeout": null}}) 到MiraiGo Element时出现错误: file not found 将忽略本段CQ码.
[2022-11-26 20:57:17] [WARNING]: 好友消息发送失败: 消息为空.
```
使用的是远程反向websocket连接（挂go-cqhttp的机器和挂nonebot的机器不是同一台，但在同一局域网内）

**Comment by Everything0519** [comment]
查了一下 大概是因为你运行nonebot和gocq的是两台机器 但是图片发送机制是是先保存在nonebot本地 然后再gocq发送 可能就是这里出了问题
可以的话查看一下这个地址有没有图片file:///C:\\Users\\YuYue\\Desktop\\yuyue_bot\\data\\nonebot-plugin-mystool/11-26-ys.jpg 如果有的话我到时候修改一下代码逻辑吧

**Comment by YuYue-Amatsuki** [comment]
> 查了一下 大概是因为你运行nonebot和gocq的是两台机器 但是图片发送机制是是先保存在nonebot本地 然后再gocq发送 可能就是这里出了问题
> 可以的话查看一下这个地址有没有图片file:///C:\\Users\\YuYue\\Desktop\\yuyue_bot\\data\\nonebot-plugin-mystool/11-26-ys.jpg 如果有的话我到时候修改一下代码逻辑吧

有的

**Comment by Everything0519** [comment]
可以尝试引入io模块 将exchangePlan.py 的329行改为
`
imagebytes = io.BytesIO(open(img_path, 'rb').read())
await get_good_image.finish(MessageSegment.image(imagebytes))
`
试试看
我刚才尝试了一下是可以正常运行的 但是我的gocq和nonebot在一台电脑上 没有办法模拟你的环境

**Comment by YuYue-Amatsuki** [comment]
> 

依旧报错
```11-27 10:14:05 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_mystool.exchangePlan) failed.
Traceback (most recent call last):
  File "C:\Users\YuYue\Desktop\yuyue_bot\bot.py", line 38, in <module>
    nonebot.run(app="__mp_main__:app")
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run
    uvicorn.run(
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 188, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher\matcher.py", line 727, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher\matcher.py", line 702, in simple_run
    await handler(
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_mystool\exchangePlan.py", line 329, in _
    imagebytes = io.BytesIO(open(img_path, 'rb').read())
NameError: name 'io' is not defined
```

**Comment by Everything0519** [comment]
需要引入io模块 在最上面任意一行import io才可以

**Comment by YuYue-Amatsuki** [comment]
> 需要引入io模块 在最上面任意一行import io才可以

可以正常发送图片了，感谢
