### ISSUE TITLE
兑换商品输入uid后报错

### ISSUE THREAD

**Issue by YuYue-Amatsuki** [Ljzd-PRO/nonebot-plugin-mystool#37]
日志如下
```
11-27 16:51:05 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_mystool.exchangePlan) failed.
Traceback (most recent call last):
  File "C:\Users\YuYue\Desktop\yuyue_bot\bot.py", line 38, in <module>
    nonebot.run(app="__mp_main__:app")
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\drivers\fastapi.py", line 172, in run
    uvicorn.run(
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 142, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 188, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher\matcher.py", line 727, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher\matcher.py", line 702, in simple_run
    await handler(
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_mystool\exchangePlan.py", line 259, in _
    exchange_plan = await Exchange(account, good.goodID, uid).async_init()
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_mystool\exchange.py", line 319, in async_init
    "address_id": self.account.address.addressID
AttributeError: 'NoneType' object has no attribute 'addressID'
```

**Comment by Everything0519** [comment]
请参考#26 该问题在开发版中已修复
该版本需要先调用/地址命令配置地址 才可以正常兑换原石这种虚拟商品
