### ISSUE TITLE
启动时报错

### ISSUE THREAD

**Issue by YuYue-Amatsuki** [Ljzd-PRO/nonebot-plugin-mystool#38]
日志如下
```
12-04 12:38:10 [ERROR] uvicorn | Traceback (most recent call last):
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 671, in lifespan
    async with self.lifespan_context(app):
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 566, in __aenter__
    await self._router.startup()
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 648, in startup
    await handler()
  File "C:\Users\YuYue\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_mystool\exchangePlan.py", line 355, in load_exchange_data
    if good_detail.time < NtpTime.time():
TypeError: '<' not supported between instances of 'NoneType' and 'float'

12-04 12:38:10 [ERROR] uvicorn | Application startup failed. Exiting.
```

**Comment by Everything0519** [comment]
尝试一下再次重启机器人 如果还是不行的话 请在userdata.json文件中删去兑换记录
顺便问下你是兑换什么商品遇到这个问题呀 我去试试看

**Comment by YuYue-Amatsuki** [comment]
> 尝试一下再次重启机器人 如果还是不行的话 请在userdata.json文件中删去兑换记录 顺便问下你是兑换什么商品遇到这个问题呀 我去试试看

![90@CM%$C`76)8R(NI2LPW5K](https://user-images.githubusercontent.com/86163024/205475619-be4741bb-a51f-497b-bf00-902cf768d531.png)
应该兑换的是这个 但是商店图片自动删除了我也不知道是什么了

**Comment by Everything0519** [comment]
好的 定位到问题了 你兑换的是原石 但是这期原石下架了 他的time属性被设置为None了
你先在userdata.json把这个兑换记录删了吧 这样机器人就可以正常启动了 现在原石也下架了 估计要下个版本才会上新了
你应该是之前原石兑换的时候没有启动机器人之类的 就没有帮你换 正常来说是会自己删除这项兑换计划的
我马上发布补丁修复哈
