### ISSUE TITLE
失败现象咨询

### ISSUE THREAD

**Issue by MWTJC** [Ljzd-PRO/nonebot-plugin-mystool#60]
我是新版真寻改版用户，功能核心代码并未改造，环境win＋py39，因不会搭建开发环境所以有此issue…
开debug日志日常测试，发现部分任务总会出现莫名其妙的失败：有返回retcode但返回的data多为null（见日志）
造成的现象就是，任务失败，
因失败现象和不同账户有关系以及总是连续出现（比如我号签到前三天不行也是null，需手动进米游社app签到，但不一定被验证码阻拦，第四天到第七天又能签到成功但，后面又会连续签到失败；便笺功能更是只连续成功过三天，之后一直失败）推测是那边服务器作祟，但我仍想在这里确认三个问题：

1. 这种失败现象是否有办法从用户这边规避？（比如用特殊办法获取特殊cookie啥的）（平台切换成我常用的安卓似乎并不奏效，似乎还是ios成功率高点也挺扯）

2. 这种失败现象是否和bot端网络情况相关？

3. 源码中似乎有对于不同失败情况作出不同提示的部分，但此种…原因可能在于米服务器的情况，源码似乎并未收录，想问下后续有无完善这部分失败提示的打算？

兔年吉祥。

```
01-26 01:33:39 [ERROR] nonebot_plugin_mystool | 原神实时便笺 - 请求失败
01-26 01:33:39 [DEBUG] nonebot_plugin_mystool | Traceback (most recent call last):
  File "F:\BOT\zhenxun_bot\extensive_plugin\nonebot_plugin_mystool\bbsAPI.py", line 699, in genshin_status_bbs
    async for attempt in tenacity.AsyncRetrying(stop=custom_attempt_times(retry), reraise=True,
  File "C:\Users\SERVER\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-EMkFGUyA-py3.9\lib\site-packages\tenacity\_asyncio.py", line 69, in __anext__
    do = self.iter(retry_state=self._retry_state)
  File "C:\Users\SERVER\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-EMkFGUyA-py3.9\lib\site-packages\tenacity\__init__.py", line 362, in iter
    raise retry_exc.reraise()
  File "C:\Users\SERVER\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-EMkFGUyA-py3.9\lib\site-packages\tenacity\__init__.py", line 195, in reraise
    raise self.last_attempt.result()
  File "C:\Python39\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\Python39\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "F:\BOT\zhenxun_bot\extensive_plugin\nonebot_plugin_mystool\bbsAPI.py", line 717, in genshin_status_bbs
    status = GenshinStatus().fromBBS(
  File "F:\BOT\zhenxun_bot\extensive_plugin\nonebot_plugin_mystool\bbsAPI.py", line 326, in fromBBS
    self.resin = status['current_resin']
TypeError: 'NoneType' object is not subscriptable
```

```
01-26 07:32:36 [INFO] nonebot_plugin_mystool | 签到: DS无效，正在在线获取salt以重新生成...
01-26 07:32:36 [INFO] nonebot_plugin_mystool | 读取配置 - 开始下载配置...
01-26 07:32:41 [INFO] nonebot_plugin_mystool | 签到: DS无效，正在在线获取salt以重新生成...
01-26 07:32:41 [INFO] nonebot_plugin_mystool | 读取配置 - 开始下载配置...
01-26 07:32:46 [INFO] nonebot_plugin_mystool | 签到: DS无效，正在在线获取salt以重新生成...
01-26 07:32:46 [INFO] nonebot_plugin_mystool | 读取配置 - 开始下载配置...
01-26 07:32:51 [INFO] nonebot_plugin_mystool | 签到: DS无效，正在在线获取salt以重新生成...
01-26 07:32:51 [INFO] nonebot_plugin_mystool | 读取配置 - 开始下载配置...
01-26 07:32:55 [INFO] github_sub | github开始检测：HibiKier/zhenxun_bot
01-26 07:32:56 [INFO] nonebot_plugin_mystool | 签到: DS无效，正在在线获取salt以重新生成...
01-26 07:32:56 [INFO] nonebot_plugin_mystool | 读取配置 - 开始下载配置...
01-26 07:33:00 [INFO] nonebot_plugin_mystool | 签到: DS无效，正在在线获取salt以重新生成...
01-26 07:33:00 [INFO] nonebot_plugin_mystool | 读取配置 - 开始下载配置...
01-26 07:33:02 [ERROR] nonebot_plugin_mystool | 签到 - 服务器没有正确返回
01-26 07:33:02 [DEBUG] nonebot_plugin_mystool | 网络请求返回: {"data":null,"message":"invalid request","retcode":-10001}
01-26 07:33:02 [DEBUG] nonebot_plugin_mystool | Traceback (most recent call last):
  File "F:\BOT\zhenxun_bot\extensive_plugin\nonebot_plugin_mystool\gameSign.py", line 324, in sign
    async for attempt in tenacity.AsyncRetrying(stop=custom_attempt_times(retry), reraise=True,
  File "C:\Users\SERVER\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-EMkFGUyA-py3.9\lib\site-packages\tenacity\_asyncio.py", line 69, in __anext__
    do = self.iter(retry_state=self._retry_state)
  File "C:\Users\SERVER\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-EMkFGUyA-py3.9\lib\site-packages\tenacity\__init__.py", line 362, in iter
    raise retry_exc.reraise()
  File "C:\Users\SERVER\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-EMkFGUyA-py3.9\lib\site-packages\tenacity\__init__.py", line 195, in reraise
    raise self.last_attempt.result()
  File "C:\Python39\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\Python39\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "F:\BOT\zhenxun_bot\extensive_plugin\nonebot_plugin_mystool\gameSign.py", line 358, in sign
    if game not in ["bh3", "wd", "bh2"] and self.signResult["data"]["risk_code"] != 0:
TypeError: 'NoneType' object is not subscriptable
```

```
01-26 07:33:24 [ERROR] nonebot_plugin_mystool | 米游币任务 - 讨论区签到: 服务器没有正确返回
01-26 07:33:24 [DEBUG] nonebot_plugin_mystool | 网络请求返回: {"data":null,"message":"","retcode":1034}
01-26 07:33:24 [DEBUG] nonebot_plugin_mystool | Traceback (most recent call last):
  File "F:\BOT\zhenxun_bot\extensive_plugin\nonebot_plugin_mystool\mybMission.py", line 203, in sign
    async for attempt in tenacity.AsyncRetrying(stop=custom_attempt_times(retry), reraise=True,
  File "C:\Users\SERVER\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-EMkFGUyA-py3.9\lib\site-packages\tenacity\_asyncio.py", line 69, in __anext__
    do = self.iter(retry_state=self._retry_state)
  File "C:\Users\SERVER\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-EMkFGUyA-py3.9\lib\site-packages\tenacity\__init__.py", line 362, in iter
    raise retry_exc.reraise()
  File "C:\Users\SERVER\AppData\Local\pypoetry\Cache\virtualenvs\zhenxun-bot-EMkFGUyA-py3.9\lib\site-packages\tenacity\__init__.py", line 195, in reraise
    raise self.last_attempt.result()
  File "C:\Python39\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\Python39\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "F:\BOT\zhenxun_bot\extensive_plugin\nonebot_plugin_mystool\mybMission.py", line 222, in sign
    return res.json()["data"]["points"]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by Ljzd-PRO** [comment]
确实可能和Cookies有关，可能用目前的方式获取的Cookies，对于一些服务它的有效期比较短。
我也是实时便笺到后面不可用，然后原神签到现在一次都不行，但崩坏3则可以。
应该不是网络问题，如果网络连接不好的话，一般会报错请求失败，请求无法发出，也不会有返回数据。

**Comment by Ljzd-PRO** [comment]
Cookies的话，可能可以每隔一段时间更新stoken，因为stoken是不需要短信验证码就可以获取的
https://github.com/Ljzd-PRO/nonebot-plugin-mystool/blob/35caf3545a91ed309b913debef0a5cbcd73d4651/src/nonebot_plugin_mystool/login.py#L119

**Comment by MWTJC** [comment]
大致明白了，感谢解答。

**Comment by Ljzd-PRO** [comment]
#32 有新的解决方案了，可以尝试。
